package de.uni_freiburg.informatik.ultimate.deltadebugger.core.search;

import java.util.List;

import de.uni_freiburg.informatik.ultimate.deltadebugger.core.IChangeHandle;
import de.uni_freiburg.informatik.ultimate.deltadebugger.core.IVariantGenerator;
import de.uni_freiburg.informatik.ultimate.deltadebugger.core.search.minimizers.DuplicateVariantTracker;
import de.uni_freiburg.informatik.ultimate.deltadebugger.core.search.minimizers.MinimizerStep;

/**
 * Holds the state of one search step for the best reduced source code variant.
 *
 * Combines the VariantGenerator and MinimizerStep interfaces into a single iterable search step that supports
 * speculative searching.
 */
public interface GeneratorSearchStep extends SearchStep<String, GeneratorSearchStep> {
	/**
	 * @return the current set of active changes to be tested
	 */
	List<IChangeHandle> getActiveChanges();

	/**
	 * @return the utilized duplicate tracker to filter duplicate variants generated by the minimizer
	 */
	DuplicateVariantTracker<IChangeHandle> getDuplicateTracker();

	/**
	 * @return the current minimizer step, holding the current set of <em>in</em>active changes
	 */
	MinimizerStep<IChangeHandle> getMinimizerStep();

	/**
	 * @return getVariantGenerator().apply(getActiveChanges())
	 */
	@Override
	String getVariant();

	/**
	 * @return the current VariantGenerator
	 */
	IVariantGenerator getVariantGenerator();

	/**
	 * Updates the duplicate tracker once the actual test result of this step is known.
	 *
	 * @param keepVariant
	 */
	default void updateDuplicateTrackerWithTestResult(final boolean keepVariant) {
		if (keepVariant) {
			getDuplicateTracker().removeLargerVariants(getMinimizerStep().getVariant().size());
		} else {
			getDuplicateTracker().add(getMinimizerStep().getVariant());
		}
	}
}