#!/bin/sh
if [ ! "$1" ]; then
    echo "First argument has to be the file that we analyze"
    exit
fi

if [ ! "$2" ]; then
    echo "No Second argument! On StarExec, the second argument is an absolute path to a directory in which we can write output for debugging. If you run this script on you machine the second argument has to be an absolute path to some directory with write access."
    exit
fi

# note this is not used at the moment, except for the check below
# mem=$((STAREXEC_MAX_MEM - 4096))
# 
# if [[ $mem -le 0 ]]; then
#     echo "star exex max memory (expected: in Mbyte) is $STAREXEC_MAX_MEM and is smaller than 4096"
#     exit 1
# fi



pushd ../Ultimate > /dev/null
./jdk-11.0.2/bin/java  -Dosgi.configuration.area=config/  -Xmx32000M -Xss4m -jar ./../Ultimate/plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar  -data "$TMPDIR" -tc ./../TreeAutomizer.xml -s ./../TreeAutomizerHopcroftMinimization.epf -i "$1" &> "$2"/output.txt
popd > /dev/null

RESULT_UNSAT=`cat "$2"/output.txt | grep "ChcUnsatResult: UNSAT"`
RESULT_SAT=`cat "$2"/output.txt | grep "ChcSatResult: SAT"`
RESULT_UNKNOWN_EXCEPTION=`cat "$2"/output.txt | grep "The toolchain threw an exception"`

if [ "$RESULT_SAT" ]; then
	echo "sat"
	exit
fi
    
if [ "$RESULT_UNSAT" ]; then
	echo "unsat"
	exit
fi
    
echo "unknown"
echo ""
cat "$2"/output.txt
