#!/bin/sh

# test if stdin or file
#if test -n "$1"; then
#    echo "Read from $1";
#elif test ! -t 0; then
#    echo "Read from stdin"
#else
#    echo "No data provided..."
#fi


[ $# -ge 1 -a -f "$1" ] && input="$1" || input="--"

pushd ../Ultimate > /dev/null
java \
-Dosgi.configuration.area=config/ \
-Xmx40G \
-Xss4m \
-jar plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar \
-data "$TMPDIR" \
-s ./../yices2.epf \
-external-solver "yices-smt2 --incremental" \
$input
popd > /dev/null

