#!/bin/sh
if [ ! "$1" ]; then
    echo "First argument has to be the file that we analyze"
    exit
fi
./../Ultimate/Ultimate -tc ./../AutomizerAndBuchiAutomizerCInlineWithBlockEncoding.xml -s ./../termcomp2017-NontrivialArrayWrites.epf -i "$1" &> output.txt

RESULT_NOTMEMSAFE=`cat output.txt | grep "CounterExampleResult"`
RESULT_PROVEN_TERMINATION=`cat output.txt | grep "Buchi Automizer proved that your program is terminating"`
RESULT_UNKNOWN_TERMINATION=`cat output.txt | grep "Buchi Automizer is unable to decide termination"`
RESULT_FALSE_TERMINATION=`cat output.txt | grep "Nonterminating execution"`

if [ "$RESULT_PROVEN_TERMINATION" ]; then
	echo "YES"
fi
    
if [ "$RESULT_FALSE_TERMINATION" ]; then
	echo "NO"
fi
    
if [ "$RESULT_UNKNOWN_TERMINATION" ]; then
	echo "MAYBE"
fi

if [ "$RESULT_NOTMEMSAFE" ]; then
	echo "MAYBE"
fi

echo ""
cat output.txt

#test if we receive output from z3
#./../z3-4.3.2.d548c51a984e-x64-debian-6.0.6/bin/z3 -h
