#! /bin/bash

# Extracts from Ultimate's output which errors are reachable/unreachable.
# usage:
#         extractResults   ULTIMATE_LOGFILE   ANALYZED_CFILE


# TODO check args
FULL_ULTIMATE_LOGFILE="$1"
ANALYZED_CFILE="$2"

CROPPED_ULTIMATE_LOGFILE=""
cleanup() { rm -f -- "$CROPPED_ULTIMATE_LOGFILE"; }
trap cleanup EXIT
CROPPED_ULTIMATE_LOGFILE="$(mktemp)"

sed -ne '/--- Results ---/,$p' -- "$FULL_ULTIMATE_LOGFILE" > "$CROPPED_ULTIMATE_LOGFILE"

extractUnreachable() {
	grep -Eo '\[Line: [0-9]+\]: call of __VERIFIER_error\(\) unreachable' -- "$CROPPED_ULTIMATE_LOGFILE" |
	grep -Eo '[0-9]+' |
	sed 's/$/\tunreachable/' 
}

extractReachable() {
	grep -Eo '\[Line: [0-9]+\]: a call of __VERIFIER_error\(\) is reachable' "$CROPPED_ULTIMATE_LOGFILE" |
	grep -Eo '[0-9]+' |
	sed 's/$/\treachable/'
}

extractAll() {
	grep -nEo '__VERIFIER_error\(.*\)' -- "$ANALYZED_CFILE" |
	grep -v "int" |
	sed 's/:/\t/'
}

sort -n \
	<(join -t $'\t' <(sort <(extractAll)) <(sort <(extractReachable))) \
	<(join -t $'\t' <(sort <(extractAll)) <(sort <(extractUnreachable)))

# TODO extractAll only once
# TODO include __VERIFIER_error without matchin reach/unreach
# TODO color output
