#! /bin/bash

# Transforms subsequent if-statemetns to if-else-statements.
#     if(c1){s1}      if(c2){s2}      if(c3){s3}
# --> if(c1){s1} else if(c2){s2} else if(c3){s3}
#
# Results are written to "Problem1?-else.c".
# Original files are not changed.

for i in Problem1?.c; do
	perl -0777 -pe 's/\}\s*if/\} else if/g' "$i" > "${i/%.c/-else.c}"
done
