#! /bin/bash

# Checks the REACHABLE results of Ultimate by applying the given traces 
# to the original programs.
# This script requires the unmodified (!) rers 2016 problems/programs. 

# Check argumengs ---------------------------------------
RESULTFILE="$1"
CFILE="$2"
if (( "$#" != 2 )); then
	echo "usage:"
	echo "       verifyReachability   RESULTS.CSV   ORIGINAL_PROBLEM.C"
	exit 1
elif [ ! -f "$RESULTFILE" ]; then
	echo "Missing file: $RESULTFILE"
	exit 1
elif [ ! -f "$CFILE" ]; then
	echo "Missing file: $CFILE"
	exit 1
fi

# Compile original problem/program ----------------------
CFILEMOD="$(basename "$CFILE" .c)mod.c"
PROGRAM="./$(basename "$CFILEMOD" .c)"
FIND='extern void __VERIFIER_error(int);'
REPLACE='void __VERIFIER_error(int e) { printf("ERROR %d\\n", e); fflush(stdout); exit(0); }'
sed "s/$FIND/$REPLACE/" -- "$CFILE" > "$CFILEMOD"
gcc -o "$PROGRAM" "$CFILEMOD" || exit 1

echo
echo "starting tests"
echo

# Apply traces and check reachability -------------------
DIFFERENCES=0
for TABLEROW in $(grep ",REACHABLE" -- "$RESULTFILE"); do
	INPUT="$(cut -d, -f4- <<< "$TABLEROW")"
	printf 'input = %s\n' "$INPUT"
	EXPECTED_ERROR_CODE="$(cut -d, -f2 <<< "$TABLEROW")"
	printf 'expected error code = %2d\n' "$EXPECTED_ERROR_CODE"
	OUTPUT="$(sed 's/,/\n/g' <<< "$INPUT" | $PROGRAM)"
	ACTUAL_ERROR_CODE="$(grep -Po "^ERROR \K-?[0-9]+$" <<< "$OUTPUT")"
	if (( EXPECTED_ERROR_CODE == ACTUAL_ERROR_CODE )); then
		printf '\033[92m' # green
	else
		printf '\033[101m' # red
		(( DIFFERENCES++ ))
	fi
	printf 'actual error code   = %2d\033[m\n\n' "$ACTUAL_ERROR_CODE"
done

if (( DIFFERENCES == 0)); then
	echo "All reachable-results are reachable"
else
	echo "Some reachable-results where not reachable using the given traces"
fi

