/* Generated by Frama-C */
typedef unsigned int size_t;
typedef int wchar_t;
/*@
axiomatic MemCmp {
  logic ℤ memcmp{L1, L2}(char *s1, char *s2, ℤ n) 
    reads \at(*(s1+(0 .. n-1)),L1), \at(*(s2+(0 .. n-1)),L2);
  
  axiom memcmp_zero{L1, L2}:
    ∀ char *s1, char *s2;
    ∀ ℤ n;
      memcmp{L1, L2}(s1, s2, n) ≡ 0 ⇔
      (∀ ℤ i; 0 ≤ i < n ⇒ \at(*(s1+i),L1) ≡ \at(*(s2+i),L2));
  
  }
 */
/*@
axiomatic MemChr {
  logic 𝔹 memchr{L}(char *s, ℤ c, ℤ n) 
    reads *(s+(0 .. n-1));
  
  axiom memchr_def{L}:
    ∀ char *s;
    ∀ ℤ c;
    ∀ ℤ n;
      memchr(s, c, n) ≡ \true ⇔ (∃ int i; 0 ≤ i < n ∧ *(s+i) ≡ c);
  
  }
 */
/*@
axiomatic MemSet {
  logic 𝔹 memset{L}(char *s, ℤ c, ℤ n) 
    reads *(s+(0 .. n-1));
  
  axiom memset_def{L}:
    ∀ char *s;
    ∀ ℤ c;
    ∀ ℤ n;
      memset(s, c, n) ≡ \true ⇔ (∀ ℤ i; 0 ≤ i < n ⇒ *(s+i) ≡ c);
  
  }
 */
/*@
axiomatic StrLen {
  logic ℤ strlen{L}(char *s) 
    reads *(s+(0 ..));
  
  axiom strlen_pos_or_null{L}:
    ∀ char *s;
    ∀ ℤ i;
      0 ≤ i ∧ (∀ ℤ j; 0 ≤ j < i ⇒ *(s+j) ≢ '\000') ∧
      *(s+i) ≡ '\000' ⇒ strlen(s) ≡ i;
  
  axiom strlen_neg{L}:
    ∀ char *s; (∀ ℤ i; 0 ≤ i ⇒ *(s+i) ≢ '\000') ⇒ strlen(s) < 0;
  
  axiom strlen_before_null{L}:
    ∀ char *s;
    ∀ ℤ i; 0 ≤ i < strlen(s) ⇒ *(s+i) ≢ '\000';
  
  axiom strlen_at_null{L}:
    ∀ char *s; 0 ≤ strlen(s) ⇒ *(s+strlen(s)) ≡ '\000';
  
  axiom strlen_not_zero{L}:
    ∀ char *s;
    ∀ ℤ i; 0 ≤ i ≤ strlen(s) ∧ *(s+i) ≢ '\000' ⇒ i < strlen(s);
  
  axiom strlen_zero{L}:
    ∀ char *s;
    ∀ ℤ i;
      0 ≤ i ≤ strlen(s) ∧ *(s+i) ≡ '\000' ⇒ i ≡ strlen(s);
  
  axiom strlen_sup{L}:
    ∀ char *s;
    ∀ ℤ i; 0 ≤ i ∧ *(s+i) ≡ '\000' ⇒ 0 ≤ strlen(s) ≤ i;
  
  axiom strlen_shift{L}:
    ∀ char *s;
    ∀ ℤ i; 0 ≤ i ≤ strlen(s) ⇒ strlen(s+i) ≡ strlen(s)-i;
  
  axiom strlen_create{L}:
    ∀ char *s;
    ∀ ℤ i; 0 ≤ i ∧ *(s+i) ≡ '\000' ⇒ 0 ≤ strlen(s) ≤ i;
  
  axiom strlen_create_shift{L}:
    ∀ char *s;
    ∀ ℤ i;
    ∀ ℤ k;
      0 ≤ k ≤ i ∧ *(s+i) ≡ '\000' ⇒ 0 ≤ strlen(s+k) ≤ i-k;
  
  axiom memcmp_strlen_left{L}:
    ∀ char *s1, char *s2;
    ∀ ℤ n;
      memcmp{L, L}(s1, s2, n) ≡ 0 ∧ strlen(s1) < n ⇒
      strlen(s1) ≡ strlen(s2);
  
  axiom memcmp_strlen_right{L}:
    ∀ char *s1, char *s2;
    ∀ ℤ n;
      memcmp{L, L}(s1, s2, n) ≡ 0 ∧ strlen(s2) < n ⇒
      strlen(s1) ≡ strlen(s2);
  
  axiom memcmp_strlen_shift_left{L}:
    ∀ char *s1, char *s2;
    ∀ ℤ k, ℤ n;
      memcmp{L, L}(s1, s2+k, n) ≡ 0 ≤ k ∧ strlen(s1) < n ⇒
      0 ≤ strlen(s2) ≤ k+strlen(s1);
  
  axiom memcmp_strlen_shift_right{L}:
    ∀ char *s1, char *s2;
    ∀ ℤ k, ℤ n;
      memcmp{L, L}(s1+k, s2, n) ≡ 0 ≤ k ∧ strlen(s2) < n ⇒
      0 ≤ strlen(s1) ≤ k+strlen(s2);
  
  }
 */
/*@
axiomatic StrCmp {
  logic ℤ strcmp{L}(char *s1, char *s2) 
    reads *(s1+(0 .. strlen(s1))), *(s2+(0 .. strlen(s2)));
  
  axiom strcmp_zero{L}:
    ∀ char *s1, char *s2;
      strcmp(s1, s2) ≡ 0 ⇔
      strlen(s1) ≡ strlen(s2) ∧
      (∀ ℤ i; 0 ≤ i ≤ strlen(s1) ⇒ *(s1+i) ≡ *(s2+i));
  
  }
 */
/*@
axiomatic StrNCmp {
  logic ℤ strncmp{L}(char *s1, char *s2, ℤ n) 
    reads *(s1+(0 .. n-1)), *(s2+(0 .. n-1));
  
  axiom strncmp_zero{L}:
    ∀ char *s1, char *s2;
    ∀ ℤ n;
      strncmp(s1, s2, n) ≡ 0 ⇔
      (strlen(s1) < n ∧ strcmp(s1, s2) ≡ 0) ∨
      (∀ ℤ i; 0 ≤ i < n ⇒ *(s1+i) ≡ *(s2+i));
  
  }
 */
/*@
axiomatic StrChr {
  logic 𝔹 strchr{L}(char *s, ℤ c) 
    reads *(s+(0 .. strlen(s)));
  
  axiom strchr_def{L}:
    ∀ char *s;
    ∀ ℤ c;
      strchr(s, c) ≡ \true ⇔
      (∃ ℤ i; 0 ≤ i ≤ strlen(s) ∧ *(s+i) ≡ c);
  
  }
 */
/*@
axiomatic WcsLen {
  logic ℤ wcslen{L}(wchar_t *s) 
    reads *(s+(0 ..));
  
  axiom wcslen_pos_or_null{L}:
    ∀ wchar_t *s;
    ∀ ℤ i;
      0 ≤ i ∧ (∀ ℤ j; 0 ≤ j < i ⇒ *(s+j) ≢ 0) ∧ *(s+i) ≡ 0 ⇒
      wcslen(s) ≡ i;
  
  axiom wcslen_neg{L}:
    ∀ wchar_t *s; (∀ ℤ i; 0 ≤ i ⇒ *(s+i) ≢ 0) ⇒ wcslen(s) < 0;
  
  axiom wcslen_before_null{L}:
    ∀ wchar_t *s;
    ∀ int i; 0 ≤ i < wcslen(s) ⇒ *(s+i) ≢ 0;
  
  axiom wcslen_at_null{L}:
    ∀ wchar_t *s; 0 ≤ wcslen(s) ⇒ *(s+wcslen(s)) ≡ 0;
  
  axiom wcslen_not_zero{L}:
    ∀ wchar_t *s;
    ∀ int i; 0 ≤ i ≤ wcslen(s) ∧ *(s+i) ≢ 0 ⇒ i < wcslen(s);
  
  axiom wcslen_zero{L}:
    ∀ wchar_t *s;
    ∀ int i; 0 ≤ i ≤ wcslen(s) ∧ *(s+i) ≡ 0 ⇒ i ≡ wcslen(s);
  
  axiom wcslen_sup{L}:
    ∀ wchar_t *s;
    ∀ int i; 0 ≤ i ∧ *(s+i) ≡ 0 ⇒ 0 ≤ wcslen(s) ≤ i;
  
  axiom wcslen_shift{L}:
    ∀ wchar_t *s;
    ∀ int i; 0 ≤ i ≤ wcslen(s) ⇒ wcslen(s+i) ≡ wcslen(s)-i;
  
  axiom wcslen_create{L}:
    ∀ wchar_t *s;
    ∀ int i; 0 ≤ i ∧ *(s+i) ≡ 0 ⇒ 0 ≤ wcslen(s) ≤ i;
  
  axiom wcslen_create_shift{L}:
    ∀ wchar_t *s;
    ∀ int i;
    ∀ int k; 0 ≤ k ≤ i ∧ *(s+i) ≡ 0 ⇒ 0 ≤ wcslen(s+k) ≤ i-k;
  
  }
 */
/*@
axiomatic WcsCmp {
  logic ℤ wcscmp{L}(wchar_t *s1, wchar_t *s2) 
    reads *(s1+(0 .. wcslen(s1))), *(s2+(0 .. wcslen(s2)));
  
  axiom wcscmp_zero{L}:
    ∀ wchar_t *s1, wchar_t *s2;
      wcscmp(s1, s2) ≡ 0 ⇔
      wcslen(s1) ≡ wcslen(s2) ∧
      (∀ ℤ i; 0 ≤ i ≤ wcslen(s1) ⇒ *(s1+i) ≡ *(s2+i));
  
  }
 */
/*@
axiomatic WcsNCmp {
  logic ℤ wcsncmp{L}(wchar_t *s1, wchar_t *s2, ℤ n) 
    reads *(s1+(0 .. n-1)), *(s2+(0 .. n-1));
  
  axiom wcsncmp_zero{L}:
    ∀ wchar_t *s1, wchar_t *s2;
    ∀ ℤ n;
      wcsncmp(s1, s2, n) ≡ 0 ⇔
      (wcslen(s1) < n ∧ wcscmp(s1, s2) ≡ 0) ∨
      (∀ ℤ i; 0 ≤ i < n ⇒ *(s1+i) ≡ *(s2+i));
  
  }
 */
/*@ logic ℤ minimum(ℤ i, ℤ j) = i<j? i: j;
 */
/*@ logic ℤ maximum(ℤ i, ℤ j) = i<j? j: i;
 */
/*@
predicate valid_string{L}(char *s) =
  0 ≤ strlen(s) ∧ \valid(s+(0 .. strlen(s)));
 */
/*@
predicate valid_read_string{L}(char *s) =
  0 ≤ strlen(s) ∧ \valid_read(s+(0 .. strlen(s)));
 */
/*@
predicate valid_string_or_null{L}(char *s) = s ≡ \null ∨ valid_string(s);
 */
/*@
predicate valid_wstring{L}(wchar_t *s) =
  0 ≤ wcslen(s) ∧ \valid(s+(0 .. wcslen(s)));
 */
/*@
predicate valid_wstring_or_null{L}(wchar_t *s) =
  s ≡ \null ∨ valid_wstring(s);
 */
/*@ ghost extern int __fc_heap_status __attribute__((__FRAMA_C_MODEL__)); */

/*@
axiomatic dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ assigns \nothing; */
extern void __VERIFIER_error(int);

void errorCheck_slice_1(void);

void calculate_output_slice_1(int input);

void calculate_outputm1_slice_1(int input);

void calculate_outputm2_slice_1(int input);

void calculate_outputm3_slice_1(int input);

void calculate_outputm5_slice_1(int input);

void calculate_outputm6_slice_1(int input);

void calculate_outputm9_slice_1(int input);

void calculate_outputm10_slice_1(int input);

void calculate_outputm12_slice_1(int input);

void calculate_outputm14_slice_1(int input);

void calculate_outputm15_slice_1(int input);

void calculate_outputm16_slice_1(int input);

void calculate_outputm17_slice_1(int input);

void calculate_outputm19_slice_1(int input);

void calculate_outputm22_slice_1(int input);

void calculate_outputm23_slice_1(int input);

void calculate_outputm24_slice_1(int input);

void calculate_outputm30_slice_1(int input);

void calculate_outputm32_slice_1(int input);

void calculate_outputm35_slice_1(int input);

void calculate_outputm39_slice_1(int input);

void calculate_outputm45_slice_1(int input);

void calculate_outputm51_slice_1(int input);

void calculate_outputm58_slice_1(int input);

void calculate_outputm75_slice_1(int input);

void calculate_outputm78_slice_1(int input);

void calculate_outputm79_slice_1(int input);

void calculate_outputm86_slice_1(int input);

void calculate_outputm98_slice_1(int input);

void calculate_outputm100_slice_1(int input);

void calculate_outputm102_slice_1(int input);

void calculate_outputm104_slice_1(int input);

void calculate_outputm105_slice_1(int input);

void calculate_outputm108_slice_1(int input);

void calculate_outputm109_slice_1(int input);

void calculate_outputm111_slice_1(int input);

void calculate_outputm123_slice_1(int input);

void calculate_outputm136_slice_1(int input);

void calculate_outputm140_slice_1(int input);

void calculate_outputm143_slice_1(int input);

int a58 = 5;
int a172 = 3;
int a187 = -193;
int a130 = 4;
int a147 = 10;
int a117 = 9;
int a100 = -50;
int a184 = 4;
int a167 = 9;
int a181 = 252;
int a159 = 143;
int a0 = 12;
int a148 = -59;
int cf = 1;
int a83 = 10;
int a156 = 34;
int a66 = 4;
int a28 = 167;
int a102 = 194;
int a166 = 12;
int a27 = 8;
int a90 = 12;
int a45 = 6;
int a81 = 65;
int a26 = 3;
int a16 = 118;
int a39 = 7;
int a120 = 145;
int a7 = 254;
int a158 = 411;
int a121 = 9;
int a119 = 6;
int a72 = 11;
int a196 = 14;
int a78 = 183;
int a61 = 10;
int a157 = 13;
int a75 = 8;
int a9 = 152;
int a180 = 70;
int a195 = 4;
int a43 = 1;
int a164 = 0;
int a68 = 1;
int a197 = 1;
int a60 = 1;
int a138 = 3;
int a33 = 1;
int a137 = 1;
int a67 = 1;
int a89 = 1;
int a76 = 1;
int a112 = 1;
int a191 = 3;
int a64 = 3;
int a151 = 1;
int a152 = 3;
int a106 = 1;
int a97 = 1;
int a88 = 2;
int a183 = 1;
int a182 = 0;
int a42 = 1;
void errorCheck_slice_1(void)
{
  if (a195 == 6) 
    if (a45 == 8) 
      if (-30 < a100) 
        if (44 >= a100) 
          /*@ slice pragma stmt; */
          __VERIFIER_error(31);
  return;
}

void calculate_outputm30_slice_1(int input)
{
  if (a130 == 4) 
    if (input == 5) 
      if (a58 <= 11) 
        if (a26 == 3) 
          if (a183 <= -29) {
            int tmp;
            { /* sequence */
              if (a33 + 20 > a33) tmp = 4; else tmp = 0;
              a33 += tmp;
            }
            cf = 0;
            a102 = ((((a102 * a16) % 14999 + 2037) % 58 + 254) * 5) % 58 - -228;
            a45 = (a26 + a130) - -1;
            a81 = (((a81 * a159) % 14999) % 93 + 179) * 1 + -1;
            a100 = ((((a100 * a9) % 14999) % 36 + 6) - -1) + 1;
            a195 = a66 + 4;
            a184 = a147 + -5;
            a9 = ((((a187 * a102) % 14999) % 31 - -192) * 1 - 18801) + 18801;
            a159 = ((((((a81 * a81) % 14999) % 32 - -171) * 9) / 10) * 5) % 32 + 174;
            a75 = a117;
            a61 = a166 + -4;
            a120 = ((((a120 * a81) % 14999) % 58 - -205) - 30139) * 1 - -30138;
            a147 = a27 - -3;
          }
  if (input == 4) 
    if (a102 <= 196) 
      if (a147 == 10) 
        if (a58 <= 11) 
          if (a187 <= -176) 
            if (a97 <= -3) {
              int tmp_0;
              { /* sequence */
                if (a68 + 20 > a68) tmp_0 = 3; else tmp_0 = 0;
                a68 += tmp_0;
              }
              cf = 0;
              a66 = a184 + 1;
            }
  if (a9 <= 159) 
    if (input == 1) 
      if (cf == 1) 
        if (a159 <= 150) 
          if (a26 == 3) 
            if (a61 == 10) 
              if (a58 <= 11) 
                if (a88 >= 12) {
                  int tmp_1;
                  { /* sequence */
                    if (a137 + 20 > a137) tmp_1 = 2; else tmp_1 = 0;
                    a137 += tmp_1;
                  }
                  cf = 0;
                  a147 = a61 - -1;
                  a187 = (((a187 * a156) % 14999) / 5 - -20102) % 107 + -164;
                  a130 = a147 - 6;
                  a117 = a130 - -5;
                  a100 = ((((a100 * a120) % 14999) / 5) / 5) % 36 + 8;
                  a184 = a130;
                  a102 = (((((a58 * a156) % 14999) * 2) % 58 + 256) * 5) % 58 - -256;
                  a45 = a166 + -10;
                  a120 = ((((a120 * a9) % 14999) % 58 + 205) - -1) - 2;
                  a9 = ((((a159 * a159) % 14999) % 31 + 190) - 0) - -2;
                  a156 = (((a156 * a102) % 14999 + 13390) / 5) % 61 + 106;
                  a159 = ((((((a159 * a16) % 14999) % 32 + 183) * 1) / 5) * 51) / 10;
                }
  if (a81 <= 84) 
    if (a117 == 9) 
      if (a26 == 3) 
        if (input == 3) 
          if (cf == 1) 
            if (a102 <= 196) {
              {
                int tmp_2;
                { /* sequence */
                  if (a68 + 20 > a68) tmp_2 = 2; else tmp_2 = 0;
                  a68 += tmp_2;
                }
                cf = 0;
                a66 = a184 * a130 - 13;
                a172 = a26 + 2;
              }
            }
  if (input == 2) 
    if (cf == 1) 
      if (a117 == 9) 
        if (a159 <= 150) 
          if (a102 <= 196) cf = 0;
  return;
}

void calculate_outputm1_slice_1(int input)
{
  if (a166 == 15) 
    if (a16 <= 125) 
      if (a83 == 10) 
        if (a120 <= 146) calculate_outputm30_slice_1(input);
  return;
}

void calculate_outputm32_slice_1(int input)
{
  if (a26 == 3) 
    if (input == 3) 
      if (a61 == 10) 
        if (a187 <= -176) {
          cf = 0;
          a9 = ((((a81 * a156) % 14999) / 5) * 5) % 34 - -257;
          a90 = a61 + 5;
          a187 = (((a9 * a81) % 14999 + -1312) % 99 + 138) - -2;
          a148 = (((((a102 * a159) % 14999) % 52 + -19) + -2) * 5) % 52 - 19;
          a16 = ((((a16 * a102) % 14999) % 54 + 344) - -1) / 5 - -306;
          a58 = ((((a58 * a81) % 14999) % 69 - -212) + 10671) + -10670;
          a100 = ((((a100 * a148) % 14999 - -11750) + 935) - 5394) % 14928 - -15071;
          a61 = a90 + -3;
          a117 = a26 - -8;
          a75 = a66 - -7;
          a147 = a26 + 9;
          a26 = a75 + -5;
          a156 = ((((a156 * a9) % 14999) % 104 + 274) + 1) / 5 - -237;
          a102 = ((((a81 * a120) % 14999 - 2316) + -9122) + 8984) % 83 - -398;
          a159 = (((a159 * a58) % 14999 + 9187) % 38 + 255) + -1;
          a130 = a66 - -3;
          a184 = a172 - -1;
          a83 = a66 - -9;
          a120 = ((((a9 * a9) % 14999) % 101 - -328) * 9) / 10 + 69;
          a27 = a83 - 2;
          a81 = ((((a81 * a187) % 14999) % 41 - -313) * 5) % 41 + 301;
        }
  if (a75 == 8) 
    if (a26 == 3) 
      if (a81 <= 84) 
        if (input == 5) 
          if (a130 == 4) {
            int tmp;
            { /* sequence */
              if (a89 + 20 > a89) tmp = 1; else tmp = 0;
              a89 += tmp;
            }
            cf = 0;
            a26 = a130;
            a45 = a172 / a61 - -1;
            a100 = (((((a100 * a9) % 14999) % 36 + 7) - 1) * 5) % 36 + 8;
            a39 = (a184 + a45) - -6;
            a120 = ((((a9 * a159) % 14999 + 4718) % 58 + 205) - -18500) - 18500;
            a27 = a172 - -4;
            a81 = ((((a81 * a159) % 14999) % 93 + 177) - 0) * 1;
            a61 = a26 + 7;
            a102 = ((((a187 * a16) % 14999 + -4951) * 1) * 1) % 58 + 256;
            a147 = a39;
            a58 = (((((a58 * a102) % 14999) % 65 - -77) * 1) * 5) % 65 - -12;
            a130 = a75 + -3;
            a184 = a27 - 4;
            a117 = a26 - -6;
            a83 = a26 + 7;
            a187 = (((a156 * a156) % 14999) % 107 - 68) / 5 + -27;
            a156 = (((a120 * a9) % 14999) % 61 + 105) / 5 - -126;
            a16 = (((((a16 * a159) % 14999) / 5) % 82 - -207) - 7111) - -7111;
            a75 = a66 + 6;
            a9 = ((((a9 * a159) % 14999) / 5) / 5) % 31 - -192;
          }
  if (a159 <= 150) 
    if (a102 <= 196) 
      if (cf == 1) 
        if (input == 4) 
          if (a147 == 10) 
            if (a156 <= 44) 
              if (a43 >= 1) {
                int tmp_1;
                { /* sequence */
                  if (a43 - 20 < a43) tmp_1 = 2; else tmp_1 = 0;
                  a43 -= tmp_1;
                }
                cf = 0;
                a120 = ((((a81 * a81) % 14999) % 58 - -204) - 0) + 2;
                a156 = (((((a120 * a120) % 14999) % 61 - -100) + 4) + 29795) - 29840;
                a184 = a130 + 1;
                a45 = a147 - 8;
                a72 = (a147 - a75) - -9;
                a102 = (((a102 * a159) % 14999) % 58 - -256) * 1 + 1;
                a58 = ((((a58 * a187) % 14999) / 5) % 65 - -77) - -1;
                a16 = ((((a16 * a156) % 14999) % 82 + 208) * 1) * 1;
                a117 = a184 + 5;
                a100 = (((a100 * a9) % 14999 + -353) + 9214) % 36 + 7;
                a27 = (a147 - a26) - -2;
                a75 = (a61 - a172) - -4;
                a9 = (((((a81 * a156) % 14999) % 31 - -191) + 29083) + 364) + -29447;
                a147 = a66 + 8;
              }
  if (a75 == 8) 
    if (a117 == 9) 
      if (a26 == 3) 
        if (a159 <= 150) 
          if (cf == 1) 
            if (input == 2) 
              if (a61 == 10) 
                if (a83 == 10) {
                  int tmp_2;
                  int tmp_4;
                  int tmp_5;
                  int tmp_6;
                  int tmp_7;
                  int tmp_8;
                  int tmp_9;
                  int tmp_10;
                  { /* sequence */
                    if (a138 + 20 > a138) tmp_2 = 2; else tmp_2 = 0;
                    a138 += tmp_2;
                  }
                  { /* sequence */
                    if (a137 - 20 < a137) tmp_4 = 4; else tmp_4 = 0;
                    a137 -= tmp_4;
                  }
                  { /* sequence */
                    if (a67 - 20 < a67) tmp_5 = 2; else tmp_5 = 0;
                    a67 -= tmp_5;
                  }
                  { /* sequence */
                    if (a89 - 20 < a89) tmp_6 = 4; else tmp_6 = 0;
                    a89 -= tmp_6;
                  }
                  { /* sequence */
                    if (a152 + 20 > a152) tmp_7 = 1; else tmp_7 = 0;
                    a152 += tmp_7;
                  }
                  { /* sequence */
                    if (a106 - 20 < a106) tmp_8 = 2; else tmp_8 = 0;
                    a106 -= tmp_8;
                  }
                  { /* sequence */
                    if (a88 + 20 > a88) tmp_9 = 2; else tmp_9 = 0;
                    a88 += tmp_9;
                  }
                  { /* sequence */
                    if (a182 + 20 > a182) tmp_10 = 2; else tmp_10 = 0;
                    a182 += tmp_10;
                  }
                  cf = 0;
                  a66 = (a172 - a130) + 5;
                  a196 = a172 - -6;
                }
  return;
}

void calculate_outputm35_slice_1(int input)
{
  if (input == 2) 
    if (a83 == 10) 
      if (a9 <= 159) {
        cf = 0;
        a66 = a83 + -4;
        a196 = a61 + 1;
      }
  if (cf == 1) 
    if (input == 3) 
      if (a83 == 10) 
        if (a61 == 10) 
          if (a130 == 4) {
            int tmp;
            int tmp_0;
            { /* sequence */
              if (a76 - 20 < a76) tmp = 4; else tmp = 0;
              a76 -= tmp;
            }
            { /* sequence */
              if (a151 - 20 < a151) tmp_0 = 3; else tmp_0 = 0;
              a151 -= tmp_0;
            }
            cf = 0;
            a39 = a26 + 8;
            a45 = a27 + -7;
            a100 = ((((a100 * a187) % 14999) % 36 + -26) + -3) + 2;
            a58 = (((a58 * a159) % 14999 - 11039) % 65 - -77) - -1;
            a184 = a117 + -4;
            a27 = a172 + 1;
            a120 = ((((a120 * a81) % 14999) * 2) % 58 + 205) / 5 + 165;
            a75 = (a39 + a39) + -13;
            a102 = ((((a159 * a81) % 14999) * 2) % 58 + 256) * 1;
            a147 = (a27 - a130) + 6;
            a156 = ((((a156 * a16) % 14999) % 61 - -105) / 5) * 5;
            a187 = (((a100 * a9) % 14999 + 14124) % 107 + -67) + -1;
            a26 = a45 * a45 - -3;
            a16 = ((a100 * a100) % 82 + 207) * 1 - -1;
            a117 = (a75 + a83) - 9;
            a61 = a66 * a66 - -2;
            a83 = a45 - -10;
            a130 = a61 * a45 + -6;
            a9 = ((((a9 * a58) % 14999) % 31 + 191) * 1 + -24461) - -24462;
            a81 = ((((a81 * a102) % 14999) % 93 - -179) * 5) / 5;
          }
  return;
}

void calculate_outputm2_slice_1(int input)
{
  if (a147 == 10) 
    if (a172 == 5) calculate_outputm32_slice_1(input);
  if (a184 == 4) 
    if (a81 <= 84) 
      if (a117 == 9) 
        if (a147 == 10) 
          if (a156 <= 44) 
            if (a172 == 8) 
              if (a120 <= 146) calculate_outputm35_slice_1(input);
  return;
}

void calculate_outputm39_slice_1(int input)
{
  if (a27 == 8) 
    if (a159 <= 150) 
      if (a102 <= 196) 
        if (a61 == 10) 
          if (input == 1) 
            if (a67 <= -3) {
              int tmp;
              { /* sequence */
                if (a68 + 20 > a68) tmp = 2; else tmp = 0;
                a68 += tmp;
              }
              cf = 0;
              a66 = a75 * a26 + -15;
            }
  if (a26 == 3) 
    if (a159 <= 150) 
      if (a130 == 4) 
        if (cf == 1) 
          if (input == 5) {
            int tmp_0;
            { /* sequence */
              if (a60 + 20 > a60) tmp_0 = 1; else tmp_0 = 0;
              a60 += tmp_0;
            }
            cf = 0;
            a26 = (a147 + a147) - 16;
            a184 = a147 + -5;
            a16 = ((36 * 10) / 2 - -65) + 25;
            a100 = ((((a100 * a9) % 14999) % 36 - -7) / 5) * 5;
            a187 = ((((a187 * a102) % 14999) % 107 - 68) - -1) - 2;
            a81 = (((a81 * a16) % 14999 + -5849) % 93 - -178) / 5 - -192;
            a120 = ((((a120 * a156) % 14999) * 2 + 1) - -1) % 58 - -205;
            a83 = a147 * a147 - 89;
            a75 = a27 * a184 - 31;
            a45 = a27;
            a102 = (((a58 * a58) % 14999 - 14015) * 1 + -710) % 58 + 256;
            a58 = ((((a58 * a159) % 14999) % 65 + 76) - -1) + 1;
            a61 = (a66 + a66) - -3;
            a27 = (a117 + a121) + -3;
            a9 = ((((a9 * a187) % 14999) / 5) % 31 - -191) - 1;
            a159 = (68 * 5) / 5 + 103;
            a130 = a147 - 5;
            a195 = a45;
            a117 = a184 - -5;
            a147 = (a130 - a130) - -11;
          }
  if (a102 <= 196) 
    if (cf == 1) 
      if (input == 2) 
        if (a61 == 10) 
          if (a58 <= 11) {
            {
              int tmp_2;
              { /* sequence */
                if (a183 + 20 > a183) tmp_2 = 2; else tmp_2 = 0;
                a183 += tmp_2;
              }
              cf = 0;
              a16 = ((87 - 6940) + 6995) + 146;
              a83 = a121 + 8;
              a184 = a130 - -1;
              a102 = ((((a16 * a16) % 14999) % 58 + 206) + 20383) - 20338;
              a45 = a147 + -2;
              a81 = ((((a81 * a102) % 14999 - -13181) * 1) * 1) % 93 + 178;
              a156 = (((a156 * a187) % 14999) % 61 - -105) * 1 + 0;
              a100 = ((((a100 * a58) % 14999) % 36 - -6) - -2) - 1;
              a120 = ((((a120 * a9) % 14999) % 58 - -204) * 5) % 58 + 184;
              a195 = a66 + 7;
              a58 = ((((a9 * a9) % 14999) % 69 - -211) - -27664) + -27662;
              a75 = a117 - -1;
              a61 = a83;
              a187 = ((((a187 * a159) % 14999 - -12668) - 8190) / 5) % 107 - 68;
              a27 = a26 + 7;
              a117 = a130 * a184 - 10;
              a9 = ((((a9 * a81) % 14999) % 31 - -190) * 1 + -3902) + 3904;
              a147 = a26 / a83 - -11;
              a159 = ((((a16 * a16) % 14999) / 5) % 32 - -162) * 1;
              a26 = a83 + -7;
              a130 = a83 - 5;
            }
          }
  if (a159 <= 150) 
    if (a58 <= 11) 
      if (cf == 1) 
        if (input == 3) 
          if (a83 == 10) 
            if (a26 == 3) 
              if (a9 <= 159) {
                int tmp_3;
                { /* sequence */
                  if (a43 - 20 < a43) tmp_3 = 1; else tmp_3 = 0;
                  a43 -= tmp_3;
                }
                cf = 0;
                a7 = ((((a159 * a9) % 14999) % 54 - -191) / 5) / 5 + 142;
                a16 = ((((a7 * a7) % 14999 + -384) % 54 - -345) - -11774) + -11773;
                a130 = (a66 + a121) - 1;
                a0 = a75 - -5;
                a61 = a27 + 4;
                a81 = ((((a16 * a7) % 14999 + 1037) % 41 + 304) * 9) / 10;
                a100 = ((((a100 * a102) % 14999) % 49 + 94) + -23989) - -23989;
                a102 = ((((a7 * a58) % 14999) % 83 - -398) - 1) + 0;
                a156 = ((((a156 * a81) % 14999) % 104 - -272) - 0) + 3;
                a187 = ((((a187 * a102) % 14999 - 7176) + -789) + 37474) % 99 - -74;
                a58 = (((((a58 * a16) % 14999) % 69 + 211) - 20901) - 2847) - -23748;
                a184 = a130;
                a9 = ((((a16 * a7) % 14999) % 34 + 237) - 12) - -8;
                a75 = a27 + 2;
                a120 = (((((a120 * a156) % 14999) % 101 + 365) - -1) - -26923) + -26924;
                a117 = a130 + 5;
                a159 = ((((a7 * a7) % 14999) / 5 - 29767) * 1) % 38 + 261;
                a147 = a130 * a26 - 6;
                a27 = a83;
                a83 = a26 + 9;
                a26 = a66 + 1;
              }
  return;
}

void calculate_outputm45_slice_1(int input)
{
  if (a27 == 8) 
    if (input == 5) 
      if (a83 == 10) 
        if (a120 <= 146) {
          cf = 0;
          a9 = (((a9 * a156) % 14999) % 31 - -192) / 5 + 175;
          a81 = ((((a9 * a9) % 14999 + 1682) % 93 + 174) * 9) / 10;
          a45 = (a75 - a26) + 1;
          a120 = ((((a120 * a81) % 14999 - -10955) - 2401) - -679) % 58 - -205;
          a100 = (((a100 * a159) % 14999 - -9296) % 36 - -7) / 5;
          a147 = a27 - -3;
          a16 = ((((a9 * a81) % 14999 + 3216) % 82 - -129) + -19435) + 19445;
          a184 = a75 - 3;
          a26 = a117 - 5;
          a157 = a66 + 7;
          a61 = a27 + 3;
          a102 = ((((a102 * a187) % 14999) % 58 + 255) + 2) * 1;
          a83 = a45 + 5;
          a187 = (((((a187 * a9) % 14999) % 107 - 68) - -6152) + -7963) + 1810;
          a58 = ((((a16 * a16) % 14999 - 9303) % 65 + 77) + 21073) - 21072;
          a130 = a121 * a147 + -94;
          a27 = a61 / a147 - -8;
          a75 = 9;
        }
  return;
}

void calculate_outputm3_slice_1(int input)
{
  if (a120 <= 146) 
    if (a81 <= 84) 
      if (a121 == 3) calculate_outputm39_slice_1(input);
  if (a16 <= 125) 
    if (a102 <= 196) 
      if (cf == 1) 
        if (a121 == 9) 
          if (a61 == 10) calculate_outputm45_slice_1(input);
  return;
}

void calculate_outputm51_slice_1(int input)
{
  if (a26 == 3) 
    if (a83 == 10) 
      if (input == 4) 
        if (a58 <= 11) 
          if (a60 <= -21) {
            int tmp;
            { /* sequence */
              if (a60 + 20 > a60) tmp = 3; else tmp = 0;
              a60 += tmp;
            }
            cf = 0;
            a117 = a196 - 1;
            a81 = ((((a159 * a58) % 14999) % 93 + 179) + 1) + -2;
            a75 = a117 - 1;
            a9 = (((((a9 * a81) % 14999) % 31 + 191) + -1) * 5) % 31 - -185;
            a39 = (a66 - a83) + 11;
            a147 = a130 - -7;
            a45 = a196 + -10;
            a100 = ((((a100 * a102) % 14999) % 36 + 8) + 1) / 5;
            a184 = a26 + 2;
            a120 = ((((a120 * a58) % 14999 + -9097) + 19646) / 5) % 58 - -205;
            a61 = a130 - -7;
            a102 = ((((a102 * a187) % 14999) % 58 + 256) + 19084) + -19083;
            a187 = (((((a187 * a58) % 14999) % 107 + -68) + 1) * 5) % 107 - 68;
            a58 = ((((a16 * a16) % 14999) % 65 - -77) * 5) / 5;
            a26 = a130;
          }
  if (a147 == 10) 
    if (input == 1) 
      if (a117 == 9) 
        if (a58 <= 11) 
          if (a197 >= 2) {
            int tmp_0;
            { /* sequence */
              if (a43 - 20 < a43) tmp_0 = 1; else tmp_0 = 0;
              a43 -= tmp_0;
            }
            cf = 0;
            a39 = a130 / a61 + 9;
            a45 = a83 + -9;
            a117 = (a39 + a196) - 10;
            a100 = (((a100 * a159) % 14999 - 5976) % 36 - -6) - 0;
            a9 = ((((a9 * a156) % 14999) % 31 - -192) - 2) - -3;
            a184 = a45 - -4;
            a27 = (a75 - a66) - -7;
            a26 = (a39 - a45) - 4;
            a120 = ((((a58 * a58) % 14999) / 5) % 58 + 204) + 1;
            a102 = ((((a102 * a120) % 14999) % 58 + 254) * 5 + -11906) % 58 + 262;
            a81 = ((((a81 * a187) % 14999 - -14995) - -4) / 5) % 93 - -135;
            a147 = a26 - -7;
            a83 = a39 + 2;
          }
  if (a26 == 3) 
    if (a27 == 8) 
      if (input == 5) 
        if (a58 <= 11) 
          if (a187 <= -176) {
            int tmp_1;
            { /* sequence */
              if (a152 - 20 < a152) tmp_1 = 4; else tmp_1 = 0;
              a152 -= tmp_1;
            }
            cf = 0;
            a66 = (a147 + a184) - 7;
            a78 = (((a100 * a9) % 14999 + -11362) % 14980 + -15019) - 2;
          }
  if (a16 <= 125) 
    if (a81 <= 84) 
      if (cf == 1) 
        if (input == 2) 
          if (a120 <= 146) 
            if (a61 == 10) 
              if (a187 <= -176) {
                int tmp_3;
                int tmp_4;
                int tmp_5;
                int tmp_6;
                { /* sequence */
                  if (a68 - 20 < a68) tmp_3 = 4; else tmp_3 = 0;
                  a68 -= tmp_3;
                }
                { /* sequence */
                  if (a197 + 20 > a197) tmp_4 = 1; else tmp_4 = 0;
                  a197 += tmp_4;
                }
                { /* sequence */
                  if (a60 - 20 < a60) tmp_5 = 4; else tmp_5 = 0;
                  a60 -= tmp_5;
                }
                { /* sequence */
                  if (a33 - 20 < a33) tmp_6 = 2; else tmp_6 = 0;
                  a33 -= tmp_6;
                }
                cf = 0;
                a121 = a26 / a196 - -3;
                a66 = a147 + -6;
              }
  return;
}

void calculate_outputm5_slice_1(int input)
{
  if (a75 == 8) 
    if (a102 <= 196) 
      if (a9 <= 159) 
        if (a196 == 11) calculate_outputm51_slice_1(input);
  return;
}

void calculate_outputm58_slice_1(int input)
{
  if (a26 == 3) 
    if (input == 1) 
      if (a61 == 10) 
        if (a89 <= -1) {
          int tmp;
          { /* sequence */
            if (a88 + 20 > a88) tmp = 2; else tmp = 0;
            a88 += tmp;
          }
          cf = 0;
          a159 = (((a159 * a187) % 14999) % 38 + 256) / 5 - -231;
          a184 = a66 + -1;
          a120 = (((((a120 * a159) % 14999) / 5) % 101 + 365) + 4471) + -4470;
          a26 = a130 + 1;
          a28 = ((a9 * a100) % 14999 - 14970) / 5 - 9874;
          a187 = ((((a187 * a58) % 14999) * 2) % 99 + 139) - -1;
          a83 = a26 + 7;
          a100 = (((((a100 * a28) % 14999) / 5) % 49 + 94) * 5) % 49 - -50;
          a7 = ((((a28 * a28) % 14999) % 14876 - -15122) - 0) * 1;
          a61 = a75 + 4;
          a75 = a130 - -6;
          a117 = (a130 + a184) - -1;
          a130 = a27 - 2;
          a102 = ((((a102 * a120) % 14999) % 83 + 399) - -1) + -2;
        }
  if (a81 <= 84) 
    if (a102 <= 196) 
      if (a16 <= 125) 
        if (input == 3) {
          {
            int tmp_1;
            { /* sequence */
              if (a183 - 20 < a183) tmp_1 = 4; else tmp_1 = 0;
              a183 -= tmp_1;
            }
            cf = 0;
            a26 = a184;
            a75 = a26 + 5;
            a147 = a75 + 2;
            a27 = a147 - 2;
            a159 = (((((a159 * a58) % 14999) * 2) % 32 - -184) * 5) % 32 - -175;
            a100 = ((((a100 * a102) % 14999) * 2 + -2) + 0) % 36 - -6;
            a58 = ((((a58 * a16) % 14999) % 65 - -77) + 19699) / 5 + -3886;
            a187 = ((((a78 * a156) % 14999) / 5) * 5) % 107 - 67;
            a45 = a130 / a130 + 3;
            a83 = a66 - -4;
            a117 = a61;
            a156 = ((((a102 * a102) % 14999) * 2) % 61 + 106) - 1;
            a16 = ((((a187 * a187) % 14999) % 82 - -207) + 0) - -1;
            a81 = ((((a102 * a9) % 14999 - -1059) + -10297) * 1) % 93 - -177;
            a120 = ((((a120 * a187) % 14999) % 58 + 205) - 1) / 5 + 200;
            a181 = (((a102 * a102) % 14999 + -14974) + -21) - 4;
            a61 = a184 + 7;
            a102 = ((((a102 * a81) % 14999) % 58 - -255) + -1) * 1;
            a130 = a26 - -1;
            a9 = (((a187 * a187) % 14999 + 10983) * 1) % 31 - -192;
            a184 = a147 + -6;
          }
        }
  if (a159 <= 150) 
    if (a156 <= 44) 
      if (a16 <= 125) 
        if (input == 2) 
          if (cf == 1) 
            if (a83 == 10) {
              int tmp_3;
              int tmp_4;
              int tmp_6;
              { /* sequence */
                if (a164 + 20 > a164) tmp_3 = 2; else tmp_3 = 0;
                a164 += tmp_3;
              }
              { /* sequence */
                if (a112 - 20 < a112) tmp_4 = 4; else tmp_4 = 0;
                a112 -= tmp_4;
              }
              { /* sequence */
                if (a43 - 20 < a43) tmp_6 = 3; else tmp_6 = 0;
                a43 -= tmp_6;
              }
              cf = 0;
              a27 = a117;
              a45 = a147 - 3;
              a117 = a66 + 2;
              a187 = ((((a187 * a81) % 14999) % 107 - 67) - 2) - -1;
              a120 = (((((a120 * a78) % 14999) * 2) % 58 - -204) * 5) % 58 + 196;
              a159 = (((a159 * a9) % 14999 - -7789) + 3321) % 32 - -184;
              a184 = a27 + -4;
              a147 = a27 * a27 - 70;
              a158 = ((((a9 * a102) % 14999) / 5 + 7913) * 10) / 9;
              a83 = (a75 - a147) + 14;
              a26 = a66 - 3;
              a100 = ((((a100 * a81) % 14999 + -11911) % 36 - -6) + 7775) - 7773;
              a81 = (((((a156 * a187) % 14999) % 93 + 179) + 1) + 10796) - 10796;
              a75 = a66 - -2;
              a156 = ((((a156 * a159) % 14999) * 2) % 15022 - 14977) * 1;
              a9 = ((((a187 * a58) % 14999 - -12798) + 642) - -1194) % 31 - -191;
              a102 = ((((a102 * a16) % 14999) % 58 + 255) - -6219) + -6219;
              a61 = a130 + 7;
              a130 = (a26 - a27) + 10;
              a16 = ((((a16 * a58) % 14999) % 82 - -208) - 1) + 0;
              a58 = ((a58 - 0) + 0) - 0;
            }
  if (a75 == 8) 
    if (a26 == 3) 
      if (cf == 1) 
        if (input == 5) 
          if (a156 <= 44) 
            if (a147 == 10) 
              if (a120 <= 146) {
                {
                  int tmp_7;
                  { /* sequence */
                    if (a43 + 20 > a43) tmp_7 = 1; else tmp_7 = 0;
                    a43 += tmp_7;
                  }
                  cf = 0;
                  a45 = (a147 - a61) + 8;
                  a184 = a75 - 3;
                  a81 = ((((a81 * a9) % 14999) * 2) % 93 + 177) / 5 - -163;
                  a195 = a27 - 4;
                  a61 = (a147 - a130) - -5;
                  a100 = ((((a100 * a187) % 14999 - 8239) % 36 + 6) * 5) % 36 + 7;
                  a156 = ((((a156 * a100) % 14999) % 61 + 105) + 0) + 1;
                  a83 = a66 - -4;
                  a159 = (((a159 * a58) % 14999 - -9153) - 13681) % 32 + 182;
                  a16 = (((((a102 * a78) % 14999) / 5) % 82 - -207) * 5) % 82 - -181;
                  a26 = a45 + -4;
                  a120 = ((((a120 * a159) % 14999) % 58 + 205) * 1) / 5 - -148;
                  a9 = (((a9 * a102) % 14999 + -8681) % 31 - -192) - 1;
                  a58 = (((((a58 * a159) % 14999) % 65 - -76) + -9121) - 18780) + 27901;
                  a75 = a147 * a45 + -71;
                  a117 = a184 * a130 + -10;
                  a27 = a26 - -5;
                  a130 = (a184 - a147) - -10;
                  a187 = ((((a187 * a16) % 14999) % 107 + -67) * 5) % 107 + -68;
                  a102 = ((((a102 * a159) % 14999) % 58 + 255) * 5) % 58 - -203;
                  a147 = a45 + 3;
                }
              }
  return;
}

void calculate_outputm6_slice_1(int input)
{
  if (a120 <= 146) 
    if (a78 <= -40) 
      if (a83 == 10) 
        if (a58 <= 11) calculate_outputm58_slice_1(input);
  return;
}

void calculate_outputm75_slice_1(int input)
{
  if (11 < a58) 
    if (142 >= a58) 
      if (a27 == 9) 
        if (a26 == 4) 
          if (input == 3) 
            if (a83 == 11) 
              if (-176 < a187) 
                if (39 >= a187) 
                  if (125 < a16) 
                    if (290 >= a16) 
                      if (a138 >= 5) {
                        int tmp_0;
                        { /* sequence */
                          if (a60 + 20 > a60) tmp_0 = 3; else tmp_0 = 0;
                          a60 += tmp_0;
                        }
                        cf = 0;
                        a9 = ((((a102 * a81) % 14999 - -11742) / -5) * 10) / 9;
                        a120 = (((a120 * a9) % 14999 + -14991) / 5) * 5;
                        a156 = ((a58 * a16) % 14999 + -20609) / 5 + -2511;
                        a66 = a83 - 3;
                        a130 = a61 + -7;
                        a184 = a83 + -7;
                        a117 = a83 - 2;
                        a195 = (a83 + a75) - 11;
                        a26 = a147 / a147 - -2;
                        a100 = ((a100 * a81 - 12200) - 4236) + -4493;
                        a75 = a61 * a27 - 91;
                        a27 = (a83 + a26) + -6;
                        a61 = a83 + -1;
                        a81 = (((a81 * a156) % 14999 - 14921) - 9) - 54;
                      }
  if (159 < a9) 
    if (146 < a120) 
      if (44 < a156) 
        if (168 >= a156) 
          if (cf == 1) 
            if (input == 5) 
              if (a83 == 11) 
                if (a184 == 5) {
                  int tmp_2;
                  { /* sequence */
                    if (a191 - 20 < a191) tmp_2 = 2; else tmp_2 = 0;
                    a191 -= tmp_2;
                  }
                  cf = 0;
                  a72 = (a26 - a27) + 13;
                  a45 = (a26 + a75) - 11;
                  a159 = (((((a81 * a58) % 14999) % 32 + 177) * 9) / 10) / 5 - -164;
                }
  if (146 < a120) 
    if (125 < a16) 
      if (290 >= a16) 
        if (a184 == 5) 
          if (cf == 1) 
            if (input == 4) 
              if (a33 <= -7) {
                int tmp_3;
                { /* sequence */
                  if (a33 + 20 > a33) tmp_3 = 4; else tmp_3 = 0;
                  a33 += tmp_3;
                }
                cf = 0;
                a66 = (a26 - a147) - -10;
                a16 = (((a16 * a187) % 14999 + 10322) + -2056) + -23187;
                a58 = ((a58 * a187 - 4723) + -422) % 15005 - 14993;
                a75 = a45 - -7;
                a117 = a184 - -4;
                a27 = a39 + -3;
                a100 = (((a100 * a102 - 20134) - -11319) - -3882) + -10879;
                a81 = ((a81 * a187) % 14999 + -14934) / 5 - 17389;
                a184 = a147 - 7;
                a102 = (((a102 * a187) % 14999 - 14809) / 5 + 15151) - 37642;
                a172 = a39 - 5;
                a61 = a130 - -5;
              }
  if (146 < a120) 
    if (input == 2) 
      if (cf == 1) 
        if (a26 == 4) 
          if (44 < a156) 
            if (168 >= a156) 
              if (a27 == 9) 
                if (125 < a16) 
                  if (290 >= a16) 
                    if (84 < a81) {
                      {
                        int tmp_4;
                        { /* sequence */
                          if (a138 - 20 < a138) tmp_4 = 1; else tmp_4 = 0;
                          a138 -= tmp_4;
                        }
                        cf = 0;
                        a26 = a39 + -6;
                        a117 = a26 - -6;
                        a100 = ((a100 * a156 + 8992) + 1756) + 5608;
                        a184 = a27 - 3;
                        a156 = (((((a187 * a16) % 14999 + -1023) % 104 - -274) + -1448) * -2) / 10;
                        a9 = (((a9 * a187) % 14999 + -627) - -660) % 34 + 257;
                        a130 = a61 - 5;
                        a27 = a26 + 5;
                        a148 = (((a81 * a120) % 14999 + 7679) - -4886) / 5;
                        a159 = (((a187 * a187) % 14999 + 3933) % 38 + 254) - 0;
                        a16 = ((((a16 * a102) % 14999 - 27302) % 54 + 379) - -6696) + -6718;
                        a83 = a39 - -1;
                        a75 = a45 - -9;
                        a58 = (((a187 * a187) % 14999 + -12302) - -18034) % 69 + 211;
                        a147 = a184 - -6;
                        a61 = a39 - -1;
                        a120 = ((((a159 * a187) % 14999) * 2) % 101 - -365) + -1;
                        a81 = ((((a159 * a102) % 14999) % 41 - -295) - 23918) - -23910;
                        a102 = (((a102 * a58) % 14999 + 2160) % 83 + 320) * 1;
                        a167 = a39 + -2;
                        a187 = ((a187 * 5) % 99 - -139) / 5 - -140;
                      }
                    }
  return;
}

void calculate_outputm9_slice_1(int input)
{
  if (a39 == 11) 
    if (a130 == 5) 
      if (a75 == 9) calculate_outputm75_slice_1(input);
  return;
}

void calculate_outputm78_slice_1(int input)
{
  if (84 < a81) 
    if (272 >= a81) 
      if (a75 == 9) 
        if (input == 5) {
          {
            int tmp_0;
            { /* sequence */
              if (a197 - 20 < a197) tmp_0 = 2; else tmp_0 = 0;
              a197 -= tmp_0;
            }
            cf = 0;
            a159 = (((a156 * a81) % 14999 + -2151) % 32 - -183) / 5 - -153;
            a72 = a26 - -4;
          }
        }
  if (a75 == 9) 
    if (146 < a120) 
      if (263 >= a120) 
        if (84 < a81) 
          if (272 >= a81) 
            if (196 < a102) 
              if (314 >= a102) 
                if (cf == 1) 
                  if (input == 3) {
                    int tmp_1;
                    { /* sequence */
                      if (a76 + 20 > a76) tmp_1 = 2; else tmp_1 = 0;
                      a76 += tmp_1;
                    }
                    cf = 0;
                    a45 = (a61 - a130) + -5;
                    a159 = ((a102 * a156) % 14999 + 4883) / 5 - 5532;
                    a39 = a147;
                  }
  if (146 < a120) 
    if (263 >= a120) 
      if (a130 == 5) 
        if (input == 2) 
          if (cf == 1) 
            if (a83 == 11) {
              {
                int tmp_3;
                { /* sequence */
                  if (a89 + 20 > a89) tmp_3 = 1; else tmp_3 = 0;
                  a89 += tmp_3;
                }
                cf = 0;
                a0 = a72 + 5;
                a61 = a0 + 1;
                a7 = ((a100 * a187 - 10203) - 3883) % 54 + 241;
                a100 = (((a100 * a58) % 49 - -94) / 5) / 5 - -114;
                a147 = a184 - -7;
                a9 = ((((a9 * a16) % 14999) / 5) % 34 + 227) / 5 - -212;
                a26 = (a61 + a45) - 9;
                a117 = a83;
                a156 = (((((a156 * a120) % 14999) % 104 - -233) + 26) * 5) % 104 + 211;
                a102 = ((((a102 * a81) % 14999) % 83 - -373) - 19491) + 19491;
                a81 = (((a9 * a9) % 14999 + -10857) % 41 - -313) + 2;
                a83 = a130 + 7;
                a130 = a27 - 3;
                a120 = ((((a120 * a9) % 14999 - -5584) + 7765) * 1) % 101 + 286;
              }
            }
  return;
}

void calculate_outputm79_slice_1(int input)
{
  if (a61 == 11) 
    if (a75 == 9) 
      if (input == 2) 
        if (a147 == 11) 
          if (146 < a120) 
            if (263 >= a120) {
              {
                int tmp;
                { /* sequence */
                  if (a76 + 20 > a76) tmp = 2; else tmp = 0;
                  a76 += tmp;
                }
                cf = 0;
              }
            }
  if (input == 1) 
    if (a75 == 9) 
      if (a151 >= 7) {
        int tmp_0;
        { /* sequence */
          if (a164 - 20 < a164) tmp_0 = 2; else tmp_0 = 0;
          a164 -= tmp_0;
        }
        cf = 0;
        a45 = a83 - 5;
        a157 = a184 + 2;
      }
  if (168 >= a156) 
    if (a75 == 9) 
      if (-176 < a187) 
        if (39 >= a187) 
          if (input == 5) 
            if (cf == 1) 
              if (a130 == 5) {
                int tmp_2;
                { /* sequence */
                  if (a64 + 20 > a64) tmp_2 = 2; else tmp_2 = 0;
                  a64 += tmp_2;
                }
                cf = 0;
                a58 = (((a187 * a159) % 14999) / 5) / 5 - 12483;
                a100 = ((a100 * a120 + -19719) + -2433) - 160;
                a83 = a130 + 5;
                a172 = a130;
                a26 = a75 * a147 + -96;
                a16 = (((a16 * a187) % 14999 + -14960) + -9) + -32;
                a61 = a130 - -5;
                a66 = a72 - 5;
                a102 = (((a102 * a120) % 14999 - -9553) - 15334) - 14625;
                a117 = a45 - -7;
                a184 = a61 + -6;
                a156 = ((a156 * a58) % 14999 + -12816) / 5 - 18505;
                a75 = (a130 - a130) + 8;
                a9 = (((a9 * a100) % 14999 + -1803) * 1 - -3279) + -8823;
                a27 = a130 * a130 - 17;
                a120 = ((((a159 * a81) % 14999) / 5 - 17858) * 10) / 9;
                a187 = ((((a58 * a58) % 14999) % 14912 + -15087) * 1 + 17077) - 17078;
                a81 = (((a58 * a58) % 14999 + -14935) / 5 - -1633) + -18267;
                a147 = (a83 - a130) - -5;
                a159 = (((a159 * a9) % 14999) / 5 - -12975) * -1;
                a130 = a83 - 6;
              }
  if (11 < a58) 
    if (input == 3) 
      if (cf == 1) 
        if (150 < a159) 
          if (125 < a16) 
            if (-176 < a187) 
              if (39 >= a187) 
                if (44 < a156) 
                  if (168 >= a156) 
                    if (a64 >= 5) {
                      int tmp_4;
                      { /* sequence */
                        if (a197 - 20 < a197) tmp_4 = 1; else tmp_4 = 0;
                        a197 -= tmp_4;
                      }
                      cf = 0;
                      a100 = ((((a100 * a156) % 49 + 93) + -15023) + 2403) + 12621;
                      a7 = (((a81 * a100) % 14999 + -5232) - -10525) * 1;
                      a130 = a75 / a27 + 5;
                      a102 = ((((a102 * a16) % 14999) % 83 + 331) - 26733) * 1 + 26731;
                      a184 = a75 + -3;
                      a159 = (((((a159 * a156) % 14999) / 5) % 38 + 251) + -21523) - -21513;
                      a61 = a26 + 8;
                      a83 = a45 + 10;
                      a187 = (((a187 * a100) / 5) / 5) % 99 - -139;
                      a117 = (a147 + a184) - 6;
                      a26 = a184 - 1;
                      a75 = a61 - 2;
                    }
  return;
}

void calculate_outputm10_slice_1(int input)
{
  if (a26 == 4) 
    if (a61 == 11) 
      if (a147 == 11) 
        if (a72 == 6) 
          if (a27 == 9) calculate_outputm78_slice_1(input);
  if (223 >= a9) 
    if (a27 == 9) 
      if (a72 == 8) 
        if (cf == 1) 
          if (a184 == 5) 
            if (150 < a159) 
              if (216 >= a159) 
                if (a26 == 4) 
                  if (196 < a102) 
                    if (314 >= a102) calculate_outputm79_slice_1(input);
  return;
}

void calculate_outputm86_slice_1(int input)
{
  if (84 < a81) 
    if (272 >= a81) 
      if (input == 2) 
        if (11 < a58) 
          if (142 >= a58) {
            cf = 0;
            a156 = ((((a156 * a120) % 14999 + -16092) + 204) - -2536) - 2615;
            a187 = ((((a156 * a156) % 14999) * 2) % 14912 - 15087) - 1;
            a83 = a26 / a27 + 10;
            a120 = (((a120 * a181) % 14999 - 14921) + -37) + -25;
            a102 = (((a102 * a187) % 14999 + 3157) * 2) * 1 - 6207;
            a147 = a130 + 5;
            a27 = a83 - 2;
            a81 = (((a187 * a187) % 14999 + -24158) + 34732) - 38605;
            a61 = a26 + 6;
            a117 = a130 + 4;
            a78 = ((((a16 * a58) % 14999 + 13237) - 40823) - -16214) - 4975;
            a66 = a130 + 2;
            a100 = ((a100 * a9 + -11474) * 1) * 1;
            a75 = (a130 + a45) - 1;
            a58 = (((a159 * a102) % 14999 + 4755) + -19755) - 2;
            a16 = (((a102 * a81) % 14999 - -4701) * 1 + 3979) + -23657;
            a9 = ((((a81 * a159) % 14999 + -14898) - 75) + 9463) + -9336;
            a26 = a130 * a130 - 22;
            a184 = a75 / a117 + 4;
            a159 = ((a159 * a156) % 14999 + -14991) * 1 + -8;
            a130 = a61 + -6;
          }
  if (-176 < a187) 
    if (39 >= a187) 
      if (a27 == 9) 
        if (input == 5) 
          if (cf == 1) 
            if (196 < a102) 
              if (a26 == 4) 
                if (a117 == 10) 
                  if (84 < a81) 
                    if (272 >= a81) {
                      int tmp;
                      { /* sequence */
                        if (a164 - 20 < a164) tmp = 2; else tmp = 0;
                        a164 -= tmp;
                      }
                      cf = 0;
                      a187 = ((a58 * a58) * 1 + -26906) * 1;
                      a102 = (((a16 * a16) % 14999 + -18600) * 1) / 5;
                      a75 = a45 + 4;
                      a172 = a27 + -4;
                      a9 = ((a9 * a187) % 14999 + -2105) / 5 + -18576;
                      a156 = (((a156 * a102) % 14999) / 5 + -14254) / 5;
                      a66 = a27 - 6;
                      a100 = ((a100 * a58 - 11560) * 1 - -15890) - 14726;
                      a120 = ((a120 * a159) % 14999 - -2547) / 5 - 19226;
                      a81 = (((a81 * a181) % 14999) / 5 + -14067) + -11028;
                      a184 = a26;
                      a130 = a117 + -6;
                      a147 = a75 - -2;
                      a27 = a61 - 3;
                      a159 = (((a187 * a187) % 14999) / 5) / 5 - 8299;
                      a117 = a26 + 5;
                      a16 = (((a9 * a58) % 14999) / 5) / 5 - 29333;
                      a83 = a61 - 1;
                      a61 = a26 + 6;
                      a58 = (((a58 * a187) % 14999 + -12350) - 1757) / 5;
                      a26 = 3;
                    }
  if (cf == 1) 
    if (input == 3) 
      if (a75 == 9) 
        if (150 < a159) 
          if (216 >= a159) 
            if (44 < a156) 
              if (-176 < a187) 
                if (39 >= a187) 
                  if (146 < a120) {
                    {
                      int tmp_3;
                      { /* sequence */
                        if (a112 + 20 > a112) tmp_3 = 4; else tmp_3 = 0;
                        a112 += tmp_3;
                      }
                      cf = 0;
                      a39 = a75 / a45 - -9;
                      a159 = (((a159 * a102) % 14999 + -17196) - -14277) - 18626;
                      a45 = a26 + -3;
                    }
                  }
  return;
}

void calculate_outputm12_slice_1(int input)
{
  if (a181 <= 162) 
    if (a83 == 11) 
      if (a130 == 5) 
        if (44 < a156) 
          if (168 >= a156) 
            if (a184 == 5) calculate_outputm86_slice_1(input);
  return;
}

void calculate_outputm98_slice_1(int input)
{
  if (84 < a81) 
    if (272 >= a81) 
      if (input == 5) 
        if (-176 < a187) 
          if (39 >= a187) {
            cf = 0;
            a102 = ((a102 * a16) % 14999 - 14902) / 5 + -3977;
            a147 = a26 - -6;
            a130 = a45 + -2;
            a187 = (((a16 * a81) % 14999 + -26510) - -16053) / 5 + -21817;
            a172 = (a26 - a75) + 10;
            a75 = a157 + -3;
            a120 = (((a120 * a81) % 14999 - 14368) - 8937) / 5;
            a83 = a117 + 1;
            a61 = (a26 - a130) + 10;
            a184 = a26 * a26 - 12;
            a100 = ((a100 * a16 - 16398) - 2356) - 1060;
            a27 = a45 * a61 - 52;
            a81 = ((((a81 * a16) % 14999 - 9888) - 5986) * 10) / 9;
            a58 = (((a58 * a187) % 14999 - 11923) - -33497) - 33373;
            a66 = a45 - 3;
            a9 = ((((a9 * a16) % 14999 + -22148) + -7784) - -25762) - 21769;
            a26 = (a147 + a184) - 11;
            a16 = ((a16 * a156) % 14999 - 14927) * 1 - 61;
          }
  return;
}

void calculate_outputm100_slice_1(int input)
{
  if (159 < a9) 
    if (223 >= a9) 
      if (input == 5) 
        if (a130 == 5) {
          {
            int tmp;
            { /* sequence */
              if (a164 - 20 < a164) tmp = 3; else tmp = 0;
              a164 -= tmp;
            }
            cf = 0;
            a158 = (((((a58 * a159) % 14999) % 74 - -183) + 5) - 15378) + 15354;
            a45 = a130 + 2;
            a117 = a184 - -5;
          }
        }
  if (44 < a156) 
    if (168 >= a156) 
      if (a75 == 9) 
        if (196 < a102) 
          if (314 >= a102) 
            if (input == 1) 
              if (146 < a120) 
                if (263 >= a120) 
                  if (a137 <= -1) {
                    int tmp_0;
                    { /* sequence */
                      if (a138 - 20 < a138) tmp_0 = 3; else tmp_0 = 0;
                      a138 -= tmp_0;
                    }
                    cf = 0;
                    a81 = (((a81 * a159) % 14999 + 2783) / 5) % 41 + 274;
                    a148 = (((((a187 * a120) % 14999) / 5) * 5) * 2) % 52 - 20;
                    a90 = a157 + 1;
                    a100 = ((a100 * a156 + 12417) * 10) / 9 + 7066;
                    a120 = (((a159 * a81) % 14999 + 13719) % 101 - -351) + -62;
                    a130 = a61 - 5;
                    a156 = (((a81 * a58) % 14999) / 5 - 8959) % 104 - -290;
                    a184 = a26 + 2;
                    a102 = ((((((a102 * a159) % 14999) % 83 - -334) + -5238) / 5) * -4) / 10;
                    a27 = (a75 + a75) + -8;
                    a9 = (((((a9 * a58) % 14999) % 34 - -242) / 5) * 10) / 2;
                    a159 = (((((a159 * a81) % 14999) % 38 + 248) - 6) + -5340) - -5315;
                  }
  if (159 < a9) 
    if (223 >= a9) 
      if (cf == 1) 
        if (input == 3) 
          if (44 < a156) 
            if (168 >= a156) 
              if (a75 == 9) {
                int tmp_1;
                { /* sequence */
                  if (a43 - 20 < a43) tmp_1 = 1; else tmp_1 = 0;
                  a43 -= tmp_1;
                }
                cf = 0;
                a120 = (((a16 * a156) % 14999 - 25197) * 10) / 9 - 525;
                a66 = a45 * a147 - 64;
                a130 = a45 / a83 - -4;
                a75 = (a45 - a83) - -13;
                a166 = a83 / a83 - -14;
                a117 = (a83 + a157) + -15;
                a26 = a61 + -8;
                a58 = (((a81 * a9) % 14999 + 9676) + -30312) * 1;
                a102 = (((a102 * a120) % 14999 - 14918) + -27) / 5;
                a159 = (((a159 * a120) % 14999) / 5) / 5 - 28742;
                a27 = a117 / a130 - -6;
                a147 = a117 / a157 + 10;
                a100 = ((a100 * a187 + 12710) + -30172) * 1;
                a61 = a45 - -4;
                a16 = (((a120 * a120) % 14999 - 6916) + 2644) / 5 + -17198;
                a184 = a147 + -6;
                a81 = (((a81 * a58) % 14999 - 14941) - 50) + -6;
                a156 = (((a120 * a120) % 14999 - 14960) - 29) + -12;
                a187 = (((a120 * a120) % 14999) % 14912 + -15087) / 5 + -2029;
                a9 = (((a120 * a120) % 14999) / 5 - 1999) * 5 + -4856;
                a83 = (a157 + a130) - 7;
              }
  if (11 < a58) 
    if (-176 < a187) 
      if (39 >= a187) 
        if (a130 == 5) 
          if (input == 2) 
            if (cf == 1) 
              if (125 < a16) 
                if (290 >= a16) 
                  if (a75 == 9) 
                    if (196 < a102) 
                      if (314 >= a102) {
                        int tmp_3;
                        { /* sequence */
                          if (a137 + 20 > a137) tmp_3 = 4; else tmp_3 = 0;
                          a137 += tmp_3;
                        }
                        cf = 0;
                        a72 = a157 + -7;
                        a117 = (a184 + a75) - 4;
                        a45 = a184 + -3;
                        a159 = (((a159 * a102) % 14999) % 38 + 224) * 1 + -7;
                      }
  return;
}

void calculate_outputm14_slice_1(int input)
{
  if (159 < a9) 
    if (223 >= a9) 
      if (a157 == 11) 
        if (a130 == 5) calculate_outputm98_slice_1(input);
  if (84 < a81) 
    if (272 >= a81) 
      if (a157 == 13) 
        if (150 < a159) 
          if (216 >= a159) 
            if (a184 == 5) calculate_outputm100_slice_1(input);
  return;
}

void calculate_outputm102_slice_1(int input)
{
  if (a83 == 11) 
    if (125 < a16) 
      if (290 >= a16) 
        if (a75 == 9) 
          if (input == 5) 
            if (159 < a9) 
              if (223 >= a9) {
                int tmp;
                { /* sequence */
                  if (a137 + 20 > a137) tmp = 4; else tmp = 0;
                  a137 += tmp;
                }
                cf = 0;
                a9 = (((a120 * a120) % 14999) / 5 - -26478) - 35466;
                a187 = ((((a187 * a9) % 14999) % 14912 - 15087) - 2) + 0;
                a66 = a61 + -8;
                a100 = ((a100 * a58 + -19373) - 5295) + -733;
                a102 = (((a102 * a158) % 14999 + -24211) + 23080) - 25007;
                a26 = a130 + -2;
                a147 = a27 * a45 - 53;
                a159 = (((a159 * a187) % 14999 + -10856) * 1 - -38456) - 36602;
                a184 = a26 + 1;
                a61 = a117;
                a83 = a75 - -1;
                a172 = a66 + 2;
                a156 = ((((a156 * a81) % 14999 - 16362) - 3265) + 29760) * -1;
                a120 = (((a120 * a9) % 14999 + -14981) + -19) * 1;
                a81 = ((((a9 * a9) % 14999) * 2) % 15042 - 14957) - 2;
                a27 = (a130 - a83) - -13;
                a58 = (((a58 * a16) % 14999 + -18945) * 10) / 9 - 437;
                a16 = (((a9 * a9) % 14999 + -14995) * 1 + 21552) + -21453;
                a130 = (a117 - a117) - -4;
                a117 = a75;
                a75 = 8;
              }
  if (input == 1) 
    if (84 < a81) 
      if (272 >= a81) 
        if (a75 == 9) 
          if (a106 <= -1) {
            int tmp_0;
            { /* sequence */
              if (a191 + 20 > a191) tmp_0 = 2; else tmp_0 = 0;
              a191 += tmp_0;
            }
            cf = 0;
            a130 = a83 + -7;
            a9 = (((a81 * a120) % 14999) / 5 - 18594) + 15474;
            a81 = (((a120 * a158) % 14999 + -25941) - 2707) + -52;
            a27 = (a147 + a130) - 7;
            a172 = a184 + 2;
            a61 = (a184 + a75) + -4;
            a100 = ((a100 * a102) * 2 - 2952) / 5 + -10600;
            a102 = ((((a9 * a156) % 14999 - 9813) - -11891) + 5703) + -22780;
            a117 = a130 * a147 - 35;
            a58 = (((a58 * a16) % 14999 - 13909) + -10354) / 5;
            a187 = ((((a187 * a120) % 14999) % 14912 + -15087) - 2) / 5 - 5196;
            a66 = a147 - 8;
            a159 = ((((a159 * a158) % 14999 - 23302) + 28053) - -4371) * -1;
            a184 = a117 + -5;
            a16 = (((a16 * a158) % 14999) / 5 - 17281) + -9942;
          }
  if (cf == 1) 
    if (input == 4) 
      if (196 < a102) 
        if (11 < a58) 
          if (a184 == 5) 
            if (a26 == 4) 
              if (a147 == 11) 
                if (a152 >= 1) {
                  int tmp_1;
                  { /* sequence */
                    if (a68 + 20 > a68) tmp_1 = 4; else tmp_1 = 0;
                    a68 += tmp_1;
                  }
                  cf = 0;
                  a166 = a184 + 7;
                  a83 = a166 + -2;
                  a100 = ((a100 * a16 - 17121) - 3667) - 191;
                  a159 = ((a158 * a102) % 14999 - 24203) * 1 + -3732;
                  a27 = a166 + -4;
                  a156 = (((a156 * a159) % 14999 - 14983) - -14200) * 1 - 14176;
                  a66 = a75 - 7;
                  a117 = a184 - -4;
                  a184 = a26;
                  a61 = a45 + 3;
                  a75 = a61 / a147 - -8;
                  a81 = ((((a81 * a187) % 14999 - -3022) + -17999) - -17588) + -17568;
                }
  if (cf == 1) 
    if (input == 3) 
      if (a117 == 10) 
        if (a61 == 11) 
          if (a147 == 11) {
            int tmp_2;
            { /* sequence */
              if (a164 - 20 < a164) tmp_2 = 3; else tmp_2 = 0;
              a164 -= tmp_2;
            }
            cf = 0;
            a187 = (((a158 * a120) % 14999 - 29588) + -113) - 91;
            a130 = (a117 + a117) - 16;
            a16 = (((a81 * a81) % 14999) / 5 + -22869) - -7793;
            a81 = ((((a81 * a187) % 14999 - 4398) * 10) / 9) * 1;
            a159 = (((a159 * a9) % 14999 + -24890) * 1 + 13126) - 15880;
            a75 = a130 - -4;
            a9 = (((a120 * a120) % 14999 + 768) / -5) / 5;
            a58 = (((a58 * a102) % 14999 - 23264) - 5284) / 5;
            a172 = (a26 - a45) + 8;
            a102 = (((a16 * a100) % 14999 - 14897) - -20479) + -20568;
            a184 = a83 * a26 + -40;
            a156 = ((a156 * a187) % 14999 - 7825) * 1 - 6792;
            a27 = (a75 - a75) - -8;
            a147 = (a172 - a117) - -15;
            a66 = a26 + -1;
            a100 = ((a100 * a120) / 5 - 23690) + -2647;
            a26 = a61 + -8;
            a61 = a130 + 6;
            a83 = a130 - -6;
            a117 = a130 + 5;
            a120 = (((a120 * a187) % 14999) / 5) / 5 - 20620;
          }
  if (196 < a102) 
    if (44 < a156) 
      if (168 >= a156) 
        if (a26 == 4) 
          if (a147 == 11) 
            if (cf == 1) 
              if (input == 2) 
                if (150 < a159) {
                  {
                    int tmp_3;
                    { /* sequence */
                      if (a97 - 20 < a97) tmp_3 = 1; else tmp_3 = 0;
                      a97 -= tmp_3;
                    }
                    cf = 0;
                    a45 = a184 - 3;
                    a72 = a130 + 3;
                  }
                }
  return;
}

void calculate_outputm104_slice_1(int input)
{
  if (-176 < a187) 
    if (input == 2) 
      if (146 < a120) 
        if (263 >= a120) 
          if (159 < a9) 
            if (223 >= a9) {
              {
                int tmp;
                { /* sequence */
                  if (a42 + 20 > a42) tmp = 2; else tmp = 0;
                  a42 += tmp;
                }
                cf = 0;
                a187 = ((((a187 * a16) % 14999 - 5145) + 13296) - 9618) % 14912 - 15087;
                a61 = a130 / a117 + 10;
                a159 = ((a159 * a158) % 14999 + -25098) * 1 + -1084;
                a196 = (a184 - a147) - -17;
                a66 = a75 + -3;
                a184 = a75 + -5;
                a27 = a26 + 4;
                a81 = (((a81 * a120) % 14999 + -23902) * 10) / 9 + -777;
                a147 = (a83 + a83) + -12;
                a130 = a27 - 4;
                a102 = (((a102 * a9) % 14999 + -26078) + -2477) - 744;
                a83 = a26 + 6;
                a100 = ((a100 * a120 - 14122) + -4738) * 1;
                a16 = (((a187 * a58) % 14999 + 13027) - 23271) + -4649;
                a9 = ((a58 * a156) % 14999 + -14874) * 1 + -88;
                a120 = (((a120 * a156) % 14999 - 14919) + -48) + -20;
                a75 = (a45 + a45) - 6;
                a26 = a45 - 4;
              }
            }
  if (a75 == 9) 
    if (125 < a16) 
      if (290 >= a16) 
        if (a147 == 11) 
          if (84 < a81) 
            if (159 < a9) 
              if (223 >= a9) 
                if (input == 3) 
                  if (cf == 1) 
                    if (a83 == 11) {
                      int tmp_0;
                      { /* sequence */
                        if (a112 + 20 > a112) tmp_0 = 3; else tmp_0 = 0;
                        a112 += tmp_0;
                      }
                      cf = 0;
                      a156 = (((a81 * a120) % 14999 + -25716) + 33301) + -23378;
                      a117 = a61 + -2;
                      a58 = (((a16 * a158) % 14999 - 27919) - 57) + -1839;
                    }
  if (a27 == 9) 
    if (a130 == 5) 
      if (196 < a102) 
        if (150 < a159) 
          if (125 < a16) 
            if (290 >= a16) 
              if (input == 5) 
                if (cf == 1) 
                  if (a26 == 4) {
                    int tmp_1;
                    { /* sequence */
                      if (a197 + 20 > a197) tmp_1 = 1; else tmp_1 = 0;
                      a197 += tmp_1;
                    }
                    cf = 0;
                    a58 = ((((a120 * a158) % 14999) % 65 - -16) - 15879) / 5 - -3281;
                    a159 = ((((a159 * a58) % 14999 + -20761) * 10) / 9) * 1;
                    a45 = a83 + -10;
                    a39 = a26 - -7;
                    a156 = ((((a102 * a187) % 14999) % 61 + 105) - -2) / 5 - -121;
                    a117 = a83 + -1;
                  }
  return;
}

void calculate_outputm15_slice_1(int input)
{
  if (263 >= a158) 
    if (a147 == 11) 
      if (44 < a156) 
        if (168 >= a156) 
          if (11 < a58) 
            if (142 >= a58) 
              if (a27 == 9) calculate_outputm102_slice_1(input);
  if (a61 == 11) 
    if (a83 == 11) 
      if (424 < a158) 
        if (cf == 1) 
          if (84 < a81) 
            if (272 >= a81) 
              if (a130 == 5) 
                if (a147 == 11) calculate_outputm104_slice_1(input);
  return;
}

void calculate_outputm105_slice_1(int input)
{
  if (a75 == 9) 
    if (146 < a120) 
      if (263 >= a120) 
        if (44 < a156) 
          if (168 >= a156) 
            if (input == 5) 
              if (a130 == 5) {
                int tmp;
                { /* sequence */
                  if (a67 + 20 > a67) tmp = 4; else tmp = 0;
                  a67 += tmp;
                }
                cf = 0;
                a159 = (((a16 * a16) % 14999) / 5) / 5 + -15696;
                a26 = (a117 + a195) - 11;
                a117 = a26 - -6;
                a156 = ((a159 * a159) % 14999 + -14956) * 1 + -38;
                a16 = (((a81 * a81) % 14999 + -17589) - 5696) + -2161;
                a172 = (a147 - a27) + 3;
                a102 = ((((a102 * a58) % 14999) / 5 - -17769) * 1) * -1;
                a187 = ((((a187 * a156) % 14999) % 14912 + -15087) - 1) - 0;
                a9 = (((a9 * a159) % 14999 - 12640) * 1) / 5 + -13439;
                a120 = (((a159 * a159) % 14999 - 6833) / 5) / 5 - 6933;
                a66 = a147 - a45;
                a27 = a26 + a130;
                a81 = (((a81 * a120) % 14999 + -3521) + -10503) - 976;
                a100 = ((a100 * a58 + 7270) * 10) / -9 + -11944;
                a61 = a83 - 1;
                a147 = a184 + 5;
                a130 = a26 + 1;
                a58 = (((a159 * a159) % 14999 - -3231) * 1 - -5613) - 23834;
                a184 = a83 - 7;
                a83 = (a195 + a75) + -3;
                a75 = a26 + 5;
              }
  if (a117 == 10) 
    if (a26 == 4) 
      if (-176 < a187) 
        if (a83 == 11) 
          if (input == 3) {
            {
              int tmp_0;
              { /* sequence */
                if (a151 + 20 > a151) tmp_0 = 2; else tmp_0 = 0;
                a151 += tmp_0;
              }
              cf = 0;
              a16 = (((a156 * a159) % 14999) / 5 + 15800) / -5;
              a102 = ((((a16 * a9) % 14999) * 2) % 15098 - 14901) / 5;
              a66 = a27 - 2;
              a100 = (a100 * a58 - 10613) / 5 + -24808;
              a147 = (a45 - a75) - -11;
              a187 = (((a187 * a58) % 14912 + -15087) + -1) - 1;
              a184 = a117 - 6;
              a156 = (((a16 * a16) % 14999) * 2) / 5 + -11645;
              a130 = a195;
              a61 = a66 + 3;
              a9 = (((a9 * a102) % 14999 + 1063) - 15929) * 1;
              a78 = ((((a100 * a81) % 14999 + 25594) * 1 + -4883) * -1) / 10;
              a120 = (((a120 * a102) % 14999 + -10388) - 4546) - 29;
              a81 = ((((a81 * a16) % 14999) * 2) % 15042 - 14957) - 1;
              a58 = ((((a16 * a16) % 14999) * 2 - 2) + 3) % 15005 - 14993;
              a26 = a130 * a75 + -33;
              a117 = a75;
              a159 = ((((a159 * a16) % 14999 - 14994) - 6) - -26447) + -26423;
              a27 = a83 - a26;
              a83 = a75 - -1;
              a75 = (a130 - a130) - -8;
            }
          }
  if (a27 == 9) 
    if (cf == 1) 
      if (input == 2) 
        if (125 < a16) 
          if (290 >= a16) {
            {
              int tmp_3;
              { /* sequence */
                if (a197 - 20 < a197) tmp_3 = 3; else tmp_3 = 0;
                a197 -= tmp_3;
              }
              cf = 0;
              a26 = a117 - 7;
              a75 = a26 - -5;
              a81 = ((((a81 * a9) % 14999 + -26296) + 40609) - -46) * -1;
              a187 = ((((a187 * a16) % 14999) % 14912 - 15087) + -1) - 1;
              a184 = a75 * a26 + -20;
              a66 = a195 * a83 - 38;
              a130 = a45 - 4;
              a100 = ((a100 * a58 + -10807) - -21326) + -30795;
              a16 = (((a81 * a120) % 14999 + 7820) + -21702) * 1 - 992;
              a58 = ((((a81 * a120) % 14999) / 5 + -19835) * 10) / 9;
              a61 = a130 + 6;
              a159 = (((a159 * a156) % 14999 + -18322) + -7642) * 1;
              a83 = a45 * a45 + -54;
              a102 = (((a102 * a120) % 14999 - 25095) * 10) / 9 + -238;
              a156 = (((a120 * a120) % 14999 + 4991) - 27858) - 4122;
              a147 = a27 + 1;
              a117 = a26 + 6;
              a9 = (((a9 * a100) % 14999 - 10122) * 10) / 9 + -1105;
              a196 = a27 + 2;
              a27 = a75 / a45 - -7;
              a120 = (((a120 * a159) % 14999 + -14930) - 16) - 14;
            }
          }
  return;
}

void calculate_outputm108_slice_1(int input)
{
  if (a75 == 9) 
    if (a130 == 5) 
      if (input == 1) 
        if (-176 < a187) 
          if (39 >= a187) 
            if (a42 <= -1) {
              int tmp;
              { /* sequence */
                if (a89 - 20 < a89) tmp = 2; else tmp = 0;
                a89 -= tmp;
              }
              cf = 0;
              a117 = a26 + 5;
              a100 = (a100 * a120 + -21724) * 1 + -38;
              a196 = a45 - -4;
              a81 = (((a81 * a102) % 14999 - -9993) * 1) / 5 + -28245;
              a120 = ((((a120 * a156) % 14999) * 2 - 2) + 0) % 15073 - 14926;
              a27 = a195 * a184 + -32;
              a147 = a45 + 2;
              a184 = a130 + -1;
              a66 = a83 + -5;
              a61 = a75 - -1;
              a130 = a75 + -5;
              a83 = a75 - -1;
            }
  if (a147 == 11) 
    if (a184 == 5) 
      if (150 < a159) 
        if (input == 3) {
          cf = 0;
          a83 = a45 + 4;
          a27 = a83 + -2;
          a180 = (((a58 * a159) % 14999 - 3706) - -11499) * 1;
          a58 = ((((((26 * 69) / 10) * 9) / 10) / 5) * 45) / 10;
          a187 = (((((87 * 10) / 9) * 9) / 10) * 9) / 10;
          a148 = (((a16 * a102) % 14999 - 17608) + 1736) % 64 + 111;
          a147 = a75 + 3;
          a26 = a27 * a117 - 95;
          a100 = ((a100 * a9) / 5) * 5 + 7997;
          a117 = a184 + 6;
          a130 = a147 / a45 + 4;
          a9 = (((((a9 * a102) % 14999) % 31 + 188) + 2) + 22394) - 22414;
          a159 = (((((a159 * a120) % 14999) / 5) % 32 + 168) - -3254) - 3262;
          a75 = a83 + -2;
          a156 = (((85 - -17246) + -17020) + -715) + 758;
          a102 = (((86 - 10022) + 10351) - 13098) + 13151;
          a16 = (((a120 * a120) % 14999 + -985) % 54 - -344) / 5 + 262;
          a81 = ((((a81 * a187) % 14999 - -14017) % 41 + 273) + 591) - 580;
          a120 = (((((a120 * a156) % 14999 - -3022) % 101 + 329) - 147) * 15) / 10;
          a61 = a147 / a83 - -11;
          a184 = a45 - 2;
        }
  return;
}

void calculate_outputm109_slice_1(int input)
{
  if (a117 == 10) 
    if (a147 == 11) 
      if (input == 3) {
        {
          int tmp;
          { /* sequence */
            if (a33 + 20 > a33) tmp = 1; else tmp = 0;
            a33 += tmp;
          }
          cf = 0;
          a81 = (((a81 * a9) % 14999 + -12373) + -5273) + -5759;
          a196 = (a26 + a184) + 2;
          a75 = a117 * a45 - 72;
          a58 = ((a81 * a81) % 14999 - 14988) / 5 + -20031;
          a187 = (((((a9 * a9) % 14999 - 19515) * 10) / 9) * 10) / 9;
          a102 = (((a102 * a9) % 14999 - 3092) - 19599) + -6865;
          a159 = (((a159 * a187) % 14999) / 5 - 18511) + -3936;
          a27 = a117 + -2;
          a184 = a75 - 4;
          a16 = (((a58 * a9) % 14999 - -13341) / 5) / 5 + -12414;
          a130 = (a45 + a45) - 12;
          a156 = (((a58 * a9) % 14999) / 5 + -8718) - 1898;
          a100 = (((a100 * a120 - -471) - 14396) + 13663) + -20563;
          a61 = a195 - 1;
          a66 = a184 * a184 + -10;
          a120 = ((((a120 * a16) % 14999 - 14886) + -54) + 4897) - 4875;
          a26 = a130 - 1;
          a117 = (a45 + a27) - 7;
          a147 = a83 + -1;
          a83 = a196 + -1;
          a9 = ((((a9 * a156) % 14999) / 5 + -4744) * 10) / 9;
        }
      }
  if (196 < a102) 
    if (input == 5) 
      if (125 < a16) 
        if (290 >= a16) 
          if (44 < a156) 
            if (168 >= a156) {
              int tmp_0;
              { /* sequence */
                if (a42 - 20 < a42) tmp_0 = 4; else tmp_0 = 0;
                a42 -= tmp_0;
              }
              cf = 0;
              a120 = ((((a120 * a187) % 14999) * 2 - 2) / 5) % 101 - -364;
              a187 = ((((a9 * a120) % 14999) % 99 - -57) * 5) % 99 + 82;
              a7 = ((((a9 * a156) % 14999 - 20906) * 1) * 10) / 9;
              a181 = ((((a7 * a7) % 14999) % 14793 + 15205) / 5) * 5 + 5;
              a156 = ((((a58 * a120) % 14999 + 12857) - -780) * 1) % 104 - -239;
              a147 = a75 - -2;
              a102 = ((((a102 * a120) % 14999) % 83 + 334) * 1) / 5 + 371;
              a26 = a195 - 6;
              a61 = a147;
              a117 = a130 - -5;
              a100 = (((a100 * a181) % 14999) % 49 - -93) * 1 + 2;
              a81 = (((a81 * a16) % 14999 - -12899) % 41 - -278) - -16;
              a16 = ((((a120 * a58) % 14999) % 54 - -291) * 5) % 54 + 293;
              a159 = (((a159 * a102) % 14999) / 5 - 11301) % 38 + 264;
              a184 = a147 - 6;
              a83 = a61;
              a9 = (((a9 * a120) % 14999 + -20378) * 1) % 34 - -284;
            }
  if (159 < a9) 
    if (223 >= a9) 
      if (input == 2) 
        if (cf == 1) 
          if (a83 == 11) 
            if (a147 == 11) 
              if (44 < a156) 
                if (168 >= a156) 
                  if (-176 < a187) 
                    if (39 >= a187) {
                      {
                        int tmp_1;
                        { /* sequence */
                          if (a164 - 20 < a164) tmp_1 = 1; else tmp_1 = 0;
                          a164 -= tmp_1;
                        }
                        cf = 0;
                      }
                    }
  return;
}

void calculate_outputm16_slice_1(int input)
{
  if (a184 == 5) 
    if (-176 < a187) 
      if (39 >= a187) 
        if (159 < a9) 
          if (223 >= a9) 
            if (a195 == 4) calculate_outputm105_slice_1(input);
  if (125 < a16) 
    if (290 >= a16) 
      if (a27 == 9) 
        if (a26 == 4) 
          if (a117 == 10) 
            if (84 < a81) 
              if (cf == 1) 
                if (a195 == 8) 
                  if (146 < a120) 
                    if (263 >= a120) calculate_outputm108_slice_1(input);
  if (a61 == 11) 
    if (a83 == 11) 
      if (a195 == 11) 
        if (cf == 1) 
          if (146 < a120) 
            if (263 >= a120) 
              if (150 < a159) 
                if (196 < a102) 
                  if (314 >= a102) calculate_outputm109_slice_1(input);
  return;
}

void calculate_outputm111_slice_1(int input)
{
  if (input == 5) 
    if (263 < a120) 
      if (a147 == 12) 
        if (223 < a9) 
          if (292 >= a9) {
            {
              int tmp;
              { /* sequence */
                if (a151 - 20 < a151) tmp = 3; else tmp = 0;
                a151 -= tmp;
              }
              cf = 0;
              a45 = a130 + 2;
              a26 = a27 - 6;
              a187 = ((((a187 * a102) % 14999 - 26462) % 107 + 37) * 5) % 107 + -67;
              a9 = ((((a120 * a102) % 14999) % 31 - -169) * 5) % 31 - -168;
              a100 = ((((a100 * a58) % 14999) % 36 - 22) + -8850) / 5 + 1752;
              a184 = a147 - 7;
              a117 = a83 + -2;
              a147 = a26 - -7;
              a156 = ((((a156 * a58) % 14999) % 61 - -58) + -14314) * 2 + 28558;
              a195 = a45 + 3;
              a83 = a75 - -1;
              a61 = a26 - -7;
              a159 = (((a159 * a16) % 14999 + -14251) / 5) % 32 + 184;
              a16 = ((((a16 * a58) % 14999) / 5) / 5 - 2026) % 82 - -253;
              a120 = (((a120 * a181) % 14999 + -3381) - -724) % 58 + 204;
              a81 = (((((a81 * a9) % 14999) % 93 + 140) * 9) / 10 + -9575) + 9610;
              a102 = (((((a102 * a7) % 14999) % 58 + 254) + 2) + -694) + 694;
            }
          }
  if (39 < a187) 
    if (238 >= a187) 
      if (a75 == 10) 
        if (input == 3) {
          int tmp_0;
          int tmp_2;
          { /* sequence */
            if (a97 - 20 < a97) tmp_0 = 2; else tmp_0 = 0;
            a97 -= tmp_0;
          }
          { /* sequence */
            if (a64 - 20 < a64) tmp_2 = 4; else tmp_2 = 0;
            a64 -= tmp_2;
          }
          cf = 0;
          a27 = a130 + 2;
          a156 = (((a156 * a9) % 14999 + -20136) - 1343) * 1;
          a26 = a27 * a83 - 93;
          a100 = ((((a100 * a16) % 14999) / 5 - 5817) - -17118) + -15949;
          a184 = (a147 - a130) + -2;
          a117 = a27 - -1;
          a120 = (((a7 * a7) % 14999 - 14993) - -22017) + -22021;
          a159 = (((a159 * a9) % 14999 - 11955) - 4482) + -4044;
          a172 = a61 - 7;
          a66 = a147 + -9;
          a81 = (((a81 * a102) % 14999 + -20769) + -2364) * 1;
          a83 = (a26 - a27) + 15;
          a61 = a130 + 4;
          a58 = ((((a58 * a7) % 14999) / 5 + -15630) * 10) / 9;
          a16 = (((a16 * a102) % 14999 - -7695) / 5) / 5 - 21990;
          a9 = ((a120 * a7) % 14999 + 12083) * 1 - 26991;
          a102 = (((a181 * a120) % 14999 - 14817) - 184) - 0;
          a75 = a27 / a130 - -7;
          a187 = ((((a187 * a120) % 14999) % 14912 + -15087) - 1) - 0;
          a147 = a27 - -2;
          a130 = a27 + -4;
        }
  return;
}

void calculate_outputm17_slice_1(int input)
{
  if (290 < a16) 
    if (412 < a181) 
      if (a184 == 6) 
        if (272 < a81) 
          if (355 >= a81) calculate_outputm111_slice_1(input);
  return;
}

void calculate_outputm123_slice_1(int input)
{
  if (142 < a58) 
    if (input == 5) {
      {
        int tmp_1;
        { /* sequence */
          if (a43 - 20 < a43) tmp_1 = 2; else tmp_1 = 0;
          a43 -= tmp_1;
        }
        cf = 0;
        a172 = a0 * a27 - 122;
        a58 = (36 * -5 + 5907) * -5;
        a100 = (((a100 * a9) % 14999 + -27039) - 2057) - 895;
        a102 = ((a58 * a100) % 14999 + -1087) * 1 + -13903;
        a75 = a184 / a184 - -7;
        a156 = (((a58 * a58) % 14999 + -14996) + -1) - 4;
        a117 = (a26 - a27) - -14;
        a16 = (((a58 * a58) % 14999) / 5 + -21663) * 1;
        a187 = ((((a187 * a102) % 14999 - 8757) * 1) * 1) % 14912 + -15087;
        a120 = (((a120 * a81) % 14999 + 5975) * 1 + -11825) - 16700;
        a66 = a172 - 5;
        a61 = a130 - -4;
        a81 = (((a81 * a16) % 14999) / 5 + 10842) / -5;
        a147 = a130 - -4;
        a9 = (((a9 * a7) % 14999 - -13353) - 17112) + -20256;
        a83 = a172 / a61 + 10;
        a159 = ((a159 * a156) % 14999 + -14968) * 1 - 31;
        a26 = a184 - 3;
        a184 = a172 - 4;
        a27 = a147 - 2;
        a130 = a117 + -5;
      }
    }
  return;
}

void calculate_outputm19_slice_1(int input)
{
  if (a0 == 13) 
    if (39 < a187) 
      if (238 >= a187) 
        if (223 < a9) 
          if (292 >= a9) calculate_outputm123_slice_1(input);
  return;
}

void calculate_outputm136_slice_1(int input)
{
  if (input == 1) 
    if (a147 == 12) 
      if (a68 <= 3) {
        int tmp;
        { /* sequence */
          if (a138 - 20 < a138) tmp = 3; else tmp = 0;
          a138 -= tmp;
        }
        cf = 0;
        a148 = ((a148 * a187 + 20573) + 1415) / 5;
        a167 = (a26 + a61) + -10;
      }
  if (290 < a16) 
    if (input == 3) 
      if (a117 == 11) 
        if (a164 >= 8) {
          cf = 0;
          a58 = ((a81 * a81) % 14999 + 1874) / 5 + -17746;
          a66 = a26 - -2;
          a61 = a147 - 2;
          a100 = (((a100 * a81) % 14999 - 7824) * 3 - -7951) % 14985 + -15014;
          a159 = (((a58 * a9) % 14999 + -9022) + -5853) - 48;
          a78 = ((((a156 * a187) % 14999 + 14549) - -79) - 29715) + 19465;
          a27 = a75 - 2;
          a184 = a147 - 8;
          a102 = ((((a102 * a120) % 14999 - 17514) + 11476) - 6623) - 4576;
          a187 = (((a16 * a159) % 14999) % 14912 - 15087) / 5 + -19263;
          a117 = a147 + -3;
          a156 = (((a100 * a159) % 14999 - 6355) * 1) / 5 - 4435;
          a81 = ((((a81 * a159) % 14999) * 2) / 5 + -5505) + -12065;
        }
  if (cf == 1) 
    if (input == 5) 
      if (216 < a159) 
        if (142 < a58) 
          if (39 < a187) {
            {
              int tmp_1;
              { /* sequence */
                if (a60 + 20 > a60) tmp_1 = 2; else tmp_1 = 0;
                a60 += tmp_1;
              }
              cf = 0;
              a130 = a117 - 6;
              a9 = ((((a156 * a156) % 14999) % 31 + 172) * 5 - -16960) % 31 + 188;
              a81 = (((a81 * a9) % 14999 - 13282) % 93 - -178) + 1;
              a26 = (a184 - a90) - -13;
              a100 = ((((a100 * a58) % 14999) % 36 - 20) + -7916) - -7914;
              a102 = (((a102 * a187) % 14999 - -9367) / 5) % 58 + 205;
              a83 = a61 + -1;
              a58 = (((a148 * a148) % 65 - -76) + 1) + 1;
              a75 = a83 * a184 - 57;
              a45 = (a184 - a184) + 6;
              a187 = (((((a187 * a16) % 14999) / 5) % 107 + -97) + -3694) - -3701;
              a27 = a147 + -3;
              a61 = a130 - -6;
              a16 = ((((a156 * a156) % 14999 - -7112) + 921) / 5) % 82 - -205;
              a159 = ((((a159 * a156) % 14999 - 6175) % 32 + 184) * 5) % 32 + 178;
              a120 = (((((a120 * a102) % 14999) % 58 - -160) * 10) / 9 - 28287) + 28263;
              a157 = a147 - -1;
              a147 = a130 + 6;
              a184 = (a130 + a130) - 5;
              a156 = (((a156 * a148) % 61 + 106) + 18083) * 1 + -18083;
            }
          }
  return;
}

void calculate_outputm22_slice_1(int input)
{
  if (a90 == 15) 
    if (39 < a187) 
      if (238 >= a187) 
        if (a83 == 12) 
          if (a75 == 10) 
            if (a26 == 5) calculate_outputm136_slice_1(input);
  return;
}

void calculate_outputm140_slice_1(int input)
{
  if (272 < a81) 
    if (a75 == 10) 
      if (a117 == 11) 
        if (142 < a58) 
          if (input == 5) {
            {
              int tmp;
              int tmp_0;
              { /* sequence */
                if (a191 + 20 > a191) tmp = 1; else tmp = 0;
                a191 += tmp;
              }
              { /* sequence */
                if (a33 + 20 > a33) tmp_0 = 1; else tmp_0 = 0;
                a33 += tmp_0;
              }
              cf = 0;
              a58 = (((a180 * a81) % 14999 + 3306) % 65 + 62) + 10;
              a195 = a147 + -8;
              a45 = a75 + -2;
              a100 = (((a100 * a102) % 14999 + -29205) % 36 + 13) + -2;
              a27 = a195 + 5;
              a75 = a117 - 2;
              a120 = (((((a120 * a180) % 14999) % 58 - -186) + -38) + -29293) - -29320;
              a184 = a83 + -7;
              a147 = a45 - -3;
              a187 = (((a81 * a159) % 14999 + 3658) % 107 + -117) / 5;
              a26 = (a184 + a75) - 10;
              a83 = a130 / a130 - -10;
              a16 = ((((a16 * a58) % 14999) % 82 - -167) - -23402) - 23413;
              a117 = 10;
              a61 = a45 - -3;
              a156 = ((a156 * a100 - -6064) % 61 + 105) + 0;
              a102 = (((a102 * a148) % 14999) / 5 - -4997) % 58 + 216;
              a81 = ((((a81 * a187) % 14999) % 93 + 178) * 1) * 1;
            }
          }
  if (input == 2) 
    if (39 < a187) 
      if (238 >= a187) 
        if (314 < a102) 
          if (a83 == 12) {
            {
              int tmp_1;
              { /* sequence */
                if (a67 + 20 > a67) tmp_1 = 1; else tmp_1 = 0;
                a67 += tmp_1;
              }
              cf = 0;
              a26 = a184 - 3;
              a117 = a147 + -3;
              a130 = a26 + 1;
              a9 = (((a81 * a81) % 14999 - -1108) + -28416) - 2198;
              a66 = a75 + -6;
              a159 = ((((a81 * a81) % 14999) / 5 + -9784) - -11784) + -25133;
              a184 = (a117 - a130) + -1;
              a121 = a75 + -7;
              a100 = (((a100 * a102) % 14999 - 24560) + -3196) + -1814;
              a187 = (((a180 * a9) % 14999) % 14912 + -15087) * 1 + -1;
              a61 = a26 / a83 + 10;
              a102 = ((((a58 * a9) % 14999) * 2) % 15098 + -14901) + 0;
              a120 = ((a120 * a9) % 14999 + 13696) * 1 + -28566;
              a83 = a26 + 7;
              a16 = ((((a16 * a148) % 14999 - 22139) + -4935) - -20648) - 14155;
              a27 = a147 * a75 + -112;
              a156 = ((a156 * a187) % 14999 + -9912) * 1 + -3497;
              a75 = a147 * a147 - 136;
              a58 = (((a159 * a81) % 14999 + -14993) + 17430) / 5 - 9072;
              a81 = (((a81 * a9) % 14999 - -12048) / 5 - -23685) * -1;
              a147 = a27 - -2;
            }
          }
  return;
}

void calculate_outputm23_slice_1(int input)
{
  if (263 < a120) 
    if (a61 == 12) 
      if (98 < a180) 
        if (290 < a16) calculate_outputm140_slice_1(input);
  return;
}

void calculate_outputm143_slice_1(int input)
{
  if (223 < a9) 
    if (292 >= a9) 
      if (input == 4) 
        if (a76 <= 3) {
          int tmp_0;
          { /* sequence */
            if (a138 - 20 < a138) tmp_0 = 4; else tmp_0 = 0;
            a138 -= tmp_0;
          }
          cf = 0;
          a184 = (a147 - a26) - 3;
          a156 = ((((a156 * a187) % 14999 + -25384) * 10) / 9) / 5;
          a26 = a117 - 8;
          a27 = a61 + -4;
          a81 = (((a81 * a148) % 14999) / 5 + -17756) * 1;
          a66 = a130 + -4;
          a100 = (((a100 * a102) % 14999 + -18872) + -7011) * 1;
          a166 = a167;
          a61 = a75;
          a117 = a27 - -1;
          a130 = (a27 - a83) + 8;
          a102 = (((a16 * a58) % 14999 - 28440) + -1023) * 1;
          a159 = ((a159 * a9) % 14999 + -23833) * 1 - -763;
          a75 = a130 - -4;
        }
  if (a147 == 12) 
    if (290 < a16) 
      if (cf == 1) 
        if (input == 3) 
          if (a75 == 10) {
            int tmp_1;
            { /* sequence */
              if (a138 - 20 < a138) tmp_1 = 1; else tmp_1 = 0;
              a138 -= tmp_1;
            }
            cf = 0;
            a39 = a27 / a167 + 10;
            a27 = a184 + 3;
            a9 = ((((a148 * a148) % 14999) % 31 + 173) + 18182) - 18170;
            a130 = a39 + -6;
            a16 = ((((a148 * a148) % 14999 - -1519) + -30065) - -5440) % 82 + 258;
            a45 = a61 + -11;
            a75 = a39 / a184 - -8;
            a26 = a39 + -7;
            a156 = (((a156 * a58) % 14999 + 4926) - -1251) % 61 + 49;
            a120 = ((((a120 * a16) % 14999) % 58 - -148) - 1) * 1;
            a100 = (((a100 * a58) % 14999 - 15625) % 36 - -43) + 1;
            a61 = a184 - -5;
            a187 = ((((a187 * a159) % 14999) / 5 + -17107) / 5) % 107 - 14;
            a117 = (a130 - a184) - -11;
            a83 = a26 + 7;
            a147 = a39;
            a58 = ((((a81 * a9) % 14999) % 65 + 38) * 9) / 10 + 36;
            a81 = ((((a81 * a102) % 14999) % 93 + 94) * 5) % 93 - -106;
            a159 = ((14 * -5 - -19682) * 1) * -1;
            a102 = ((((a120 * a120) % 14999) % 58 - -249) * 5 - -15644) % 58 + 202;
            a184 = a26 + 1;
          }
  if (a26 == 5) 
    if (a184 == 6) 
      if (272 < a81) 
        if (263 < a120) 
          if (a61 == 12) 
            if (cf == 1) 
              if (input == 5) 
                if (a112 <= -5) {
                  int tmp_2;
                  { /* sequence */
                    if (a43 - 20 < a43) tmp_2 = 2; else tmp_2 = 0;
                    a43 -= tmp_2;
                  }
                  cf = 0;
                  a100 = (((a100 * a159) % 14999) / 5 - 20433) - 5054;
                  a66 = a61 * a61 + -139;
                  a61 = a130 + 4;
                  a9 = ((((a100 * a16) % 14999) / 5 - 4199) * 10) / 9;
                  a184 = a61 - 6;
                  a102 = (((a16 * a81) % 14999 + -26837) - 2575) + -278;
                  a119 = a75 / a27 - -5;
                  a120 = ((((a120 * a102) % 14999 + -14906) + -20) + 24700) + -24683;
                  a58 = (((a58 * a187) % 14999 - 25325) + -2494) / 5;
                  a156 = (((a156 * a9) % 14999 + -14972) - 16) - 12;
                  a26 = a119 - 3;
                  a117 = (a83 + a61) + -13;
                  a27 = a184 + 4;
                  a147 = (a130 - a75) + 14;
                  a81 = ((((a81 * a9) % 14999) * 2) % 15042 - 14957) - 0;
                }
  if (a117 == 11) 
    if (input == 2) 
      if (cf == 1) 
        if (a26 == 5) 
          if (a184 == 6) 
            if (a130 == 6) 
              if (216 < a159) 
                if (314 < a102) 
                  if (a191 >= 1) {
                    int tmp_3;
                    { /* sequence */
                      if (a67 + 20 > a67) tmp_3 = 1; else tmp_3 = 0;
                      a67 += tmp_3;
                    }
                    a27 = a117 - 2;
                    a45 = a75 * a26 - 47;
                    a100 = (((((a100 * a148) % 14999) % 36 - 20) - -5390) * 5) % 36 + 5;
                    a147 = a167 - -2;
                    a102 = (((a9 * a120) % 14999 + 10604) + -35319) % 58 + 304;
                    a181 = (a100 * a16 - -12026) * 1 - -2;
                    a58 = ((((a58 * a100) * 2) / 5) * 5) % 65 + 77;
                    a9 = ((((a9 * a159) % 14999 - -6557) + 904) + 5996) % 31 - -176;
                    a120 = ((((a120 * a102) % 14999) % 58 - -174) * 10) / 9 + -18;
                    a184 = a83 * a83 + -139;
                    a81 = ((((a81 * a187) % 14999 - -292) % 93 - -158) - -16495) + -16487;
                    a26 = a45 - -1;
                  }
  return;
}

void calculate_outputm24_slice_1(int input)
{
  if (39 < a187) 
    if (238 >= a187) 
      if (a167 == 9) 
        if (a83 == 12) 
          if (272 < a81) 
            if (168 < a156) calculate_outputm143_slice_1(input);
  return;
}

void calculate_output_slice_1(int input)
{
  cf = 1;
  if (a184 == 4) 
    if (a81 <= 84) 
      if (a117 == 9) 
        if (a27 == 8) 
          if (a100 <= -30) 
            if (a61 == 10) {
              if (a156 <= 44) 
                if (a66 == 2) 
                  if (a75 == 8) 
                    if (a159 <= 150) calculate_outputm1_slice_1(input);
              if (a184 == 4) 
                if (a58 <= 11) 
                  if (a16 <= 125) 
                    if (a159 <= 150) 
                      if (a102 <= 196) 
                        if (a66 == 3) 
                          if (cf == 1) 
                            if (a117 == 9) calculate_outputm2_slice_1(input);
              if (a156 <= 44) 
                if (a75 == 8) 
                  if (a9 <= 159) 
                    if (a66 == 4) 
                      if (cf == 1) 
                        if (a187 <= -176) calculate_outputm3_slice_1(input);
              if (a61 == 10) 
                if (cf == 1) 
                  if (a66 == 6) 
                    if (a130 == 4) 
                      if (a184 == 4) 
                        if (a147 == 10) 
                          if (a156 <= 44) 
                            if (a81 <= 84) calculate_outputm5_slice_1(input);
              if (a27 == 8) 
                if (a156 <= 44) 
                  if (a159 <= 150) 
                    if (a102 <= 196) 
                      if (a66 == 7) 
                        if (cf == 1) 
                          if (a187 <= -176) calculate_outputm6_slice_1
                                            (input);
            }
  if (159 < a9) 
    if (223 >= a9) 
      if (146 < a120) 
        if (263 >= a120) 
          if (a184 == 5) 
            if (196 < a102) 
              if (314 >= a102) 
                if (a147 == 11) 
                  if (cf == 1) 
                    if (-30 < a100) 
                      if (44 >= a100) {
                        if (a117 == 10) 
                          if (84 < a81) 
                            if (272 >= a81) 
                              if (a45 == 1) calculate_outputm9_slice_1
                                            (input);
                        if (a45 == 2) 
                          if (cf == 1) 
                            if (11 < a58) 
                              if (142 >= a58) 
                                if (125 < a16) 
                                  if (290 >= a16) 
                                    if (159 < a9) 
                                      if (223 >= a9) 
                                        if (a117 == 10) 
                                          if (44 < a156) 
                                            if (168 >= a156) calculate_outputm10_slice_1
                                                             (input);
                        if (a147 == 11) 
                          if (a27 == 9) 
                            if (a61 == 11) 
                              if (159 < a9) 
                                if (223 >= a9) 
                                  if (146 < a120) 
                                    if (263 >= a120) 
                                      if (a45 == 4) 
                                        if (cf == 1) 
                                          if (196 < a102) 
                                            if (314 >= a102) calculate_outputm12_slice_1
                                                             (input);
                        if (a61 == 11) 
                          if (a45 == 6) 
                            if (cf == 1) 
                              if (a27 == 9) 
                                if (a83 == 11) 
                                  if (11 < a58) 
                                    if (142 >= a58) 
                                      if (a26 == 4) calculate_outputm14_slice_1
                                                    (input);
                        if (a130 == 5) 
                          if (a45 == 7) 
                            if (cf == 1) 
                              if (-176 < a187) 
                                if (39 >= a187) 
                                  if (a184 == 5) 
                                    if (150 < a159) 
                                      if (216 >= a159) 
                                        if (196 < a102) 
                                          if (314 >= a102) calculate_outputm15_slice_1
                                                           (input);
                        if (84 < a81) 
                          if (272 >= a81) 
                            if (cf == 1) 
                              if (a45 == 8) 
                                if (196 < a102) 
                                  if (314 >= a102) 
                                    if (a61 == 11) 
                                      if (150 < a159) 
                                        if (216 >= a159) 
                                          if (a147 == 11) calculate_outputm16_slice_1
                                                          (input);
                      }
  if (44 < a100) 
    if (143 >= a100) 
      if (cf == 1) 
        if (314 < a102) 
          if (a26 == 5) 
            if (a61 == 12) 
              if (a117 == 11) 
                if (a130 == 6) 
                  if (216 < a159) {
                    if (a7 <= 54) 
                      if (a83 == 12) 
                        if (168 < a156) 
                          if (378 >= a156) 
                            if (a27 == 10) calculate_outputm17_slice_1
                                           (input);
                    if (263 < a120) 
                      if (a61 == 12) 
                        if (272 < a81) 
                          if (355 >= a81) 
                            if (a83 == 12) 
                              if (a117 == 11) 
                                if (cf == 1) 
                                  if (137 < a7) 
                                    if (246 >= a7) calculate_outputm19_slice_1
                                                   (input);
                  }
  if (cf == 1) 
    if (143 < a100) 
      if (272 < a81) 
        if (355 >= a81) 
          if (263 < a120) 
            if (314 < a102) 
              if (a184 == 6) 
                if (168 < a156) 
                  if (378 >= a156) {
                    if (a130 == 6) 
                      if (32 >= a148) 
                        if (216 < a159) 
                          if (223 < a9) 
                            if (292 >= a9) 
                              if (a27 == 10) calculate_outputm22_slice_1
                                             (input);
                    if (a147 == 12) 
                      if (a184 == 6) 
                        if (a26 == 5) 
                          if (168 < a156) 
                            if (cf == 1) 
                              if (32 < a148) 
                                if (162 >= a148) 
                                  if (a27 == 10) calculate_outputm23_slice_1
                                                 (input);
                    if (a75 == 10) 
                      if (cf == 1) 
                        if (162 < a148) 
                          if (a61 == 12) 
                            if (a27 == 10) 
                              if (a184 == 6) 
                                if (142 < a58) 
                                  if (a26 == 5) calculate_outputm24_slice_1
                                                (input);
                  }
  errorCheck_slice_1();
  return;
}

extern int ( /* missing proto */ __VERIFIER_nondet_int)();

void main(void)
{
  while (1) {
    {
      int input;
      input = __VERIFIER_nondet_int();
      if (input != 2) 
        if (input != 5) 
          if (input != 3) 
            if (input != 1) 
              if (input != 4) goto return_label;
      calculate_output_slice_1(input);
    }
  }
  return_label: return;
}


