---
engines:
 duplication:
   enabled: true
 metrics:
   enabled: true
 coverage:
   enabled: true
exclude_paths:
  - **/src/jdd/**,
  - **/src/net/sf/javabdd/**,
  - **/src/com/github/jhoenicke/javacup/**,
  - **/src/org/apache/commons/cli/**,
  - **/src/srParse/ReqLexer.java,
  - **/src/srParse/ReqParser.java,
  - **/src/srParse/ReqSymbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/model/acsl/ast/*.java,
  - **/src/de/uni_freiburg/informatik/ultimate/acsl/parser/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/acsl/parser/Scanner.java,
  - **/src/de/uni_freiburg/informatik/ultimate/acsl/parser/sym.java,
  - **/src/de/uni_freiburg/informatik/ultimate/astbuilder/parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/astbuilder/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/astbuilder/sym.java,
  - **/src/de/uni_freiburg/informatik/ultimate/astbuilder/Node.java,
  - **/src/de/uni_freiburg/informatik/ultimate/astbuilder/Parameter.java,
  - **/src/de/uni_freiburg/informatik/ultimate/astbuilder/Grammar.java,
  - **/src/de/uni_freiburg/informatik/ultimate/plugins/source/automatascriptparser/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/plugins/source/automatascriptparser/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/plugins/source/automatascriptparser/sym.java,
  - **/src/de/uni_freiburg/informatik/ultimate/boogie/ast/*.java,
  - **/src/de/uni_freiburg/informatik/ultimate/boogie/parser/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/boogie/parser/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/boogie/parser/LexerSymbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/ltl2aut/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/ltl2aut/LexerAP.java,
  - **/src/de/uni_freiburg/informatik/ultimate/ltl2aut/SymbolsAP.java,
  - **/src/de/uni_freiburg/informatik/ultimate/ltl2aut/Symbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/ltl2aut/ParserAP.java,
  - **/src/de/uni_freiburg/informatik/ultimate/ltl2aut/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/dimacs/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/dimacs/LexerSymbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/dimacs/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib/LexerSymbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib2/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib2/LexerSymbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtinterpol/smtlib2/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtsolver/external/Lexer.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtsolver/external/LexerSymbols.java,
  - **/src/de/uni_freiburg/informatik/ultimate/smtsolver/external/Parser.java,
  - **/src/de/uni_freiburg/informatik/ultimate/plugins/spaceex/parser/generated/*.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/DropmodelType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/ModelIdOnlyType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/ObjectFactory.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/PluginType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/SerializeType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/SubchainType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/ToolchainListType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/ToolchainModelType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/OptionType.java,
  - **/src/de/uni_freiburg/informatik/ultimate/core/lib/toolchain/RunDefinition.java
  - **/src/de/uni_freiburg/informatik/ultimate/interactive/traceabstraction/protobuf/*.* 
  - **/src/de/uni_freiburg/informatik/ultimate/interactive/common/protobuf/*.* 
  - **/src/de/uni_freiburg/informatik/ultimate/servercontroller/protobuf/*.*
