#!/bin/sh
if [ ! "$1" ]; then
    echo "First argument has to be the file that we analyze"
    exit
fi
./../Ultimate/Ultimate -tc ./../AutomizerCHC.xml -s ./../chcToBoogie_automizer.epf -data "$TMPDIR" -i "$1" &> output.txt

RESULT_UNSAFE=`cat output.txt | grep "CounterExampleResult"`
RESULT_SAFE=`cat output.txt | grep "PositiveResult"`
RESULT_UNKNOWN_EXCEPTION =`cat output.txt | grep "The toolchain threw an exception"`

if [ "$RESULT_SAFE" ]; then
	echo "SAT"
fi
    
if [ "$RESULT_UNSAFE" ]; then
	echo "UNSAT"
fi
    
if [ "$RESULT_UNKNOWN_EXCEPTION" ]; then
	echo "UNKNOWN"
fi


echo ""
cat output.txt

