--- original_Mjollnir/trunk/Makefile	2012-02-24 06:29:51.000000000 +0100
+++ Mjollnir/trunk/Makefile	2012-11-27 12:34:56.000000000 +0100
@@ -88,7 +92,7 @@
 %.cmx : %.ml
 	$(OCAMLOPT) $(OCAMLFLAGS) -c $<
 
-PARSER_CMO = formula_lira.cmo formula_redlog.cmo parser_helper.cmo formula_parser.cmo formula_lexer.cmo lira_parser.cmo lira_lexer.cmo smtlib.cmo Dutertre/smtlib_parser.cmo Dutertre/smtlib_tokenizer.cmo
+PARSER_CMO = formula_lira.cmo formula_smtlib.cmo formula_redlog.cmo parser_helper.cmo formula_parser.cmo formula_lexer.cmo lira_parser.cmo lira_lexer.cmo smtlib.cmo Dutertre/smtlib_parser.cmo Dutertre/smtlib_tokenizer.cmo
 PARSER_CMX = $(PARSER_CMO:.cmo=.cmx)
 
 QELIM_ENGINE_BYTE = $(QELIM_ENGINE_CMO) $(QELIM_ENGINE_O)
