#!/bin/sh
if [ ! "$1" ]; then
    echo "First argument has to be the file that we analyze"
    exit
fi
mem=$((STAREXEC_MAX_MEM - 4096))

if [[ $mem -le 0 ]]; then
    echo "star exex max memory (expected: in Mbyte) is $STAREXEC_MAX_MEM and is smaller than 4096"
    exit 1
fi


if [ -z $2 ]
then
	path="."
else
	path=$2
fi

outputfile=$path/output.txt


java  -Dosgi.configuration.area=config/  -Xmx54000M -Xss4m -jar ./../Ultimate/plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar  -data "$TMPDIR" -tc ./../TreeAutomizer.xml -s ./../TreeAutomizerHopcroftMinimization.epf -i "$1" &> $outputfile

RESULT_UNSAT=`cat $outputfile | grep "TreeAutomizerUnsatResult"`
RESULT_SAT=`cat $outputfile | grep "TreeAutomizerSatResult"`
RESULT_UNKNOWN_EXCEPTION=`cat $outputfile | grep "The toolchain threw an exception"`

if [ "$RESULT_SAT" ]; then
	echo "sat"
	exit
fi
    
if [ "$RESULT_UNSAT" ]; then
	echo "unsat"
	exit
fi
    
echo "unknown"
echo ""
cat $outputfile
