#! /bin/bash

for i in {10..18}; do
	echo
	echo "$i ---------------"
	comm \
		<(cut -d' ' -f1 "result$i.txt" | sort) \
		<(grep -Fv '#' "../bruteforce/result$i.txt" | cut -d' ' -f1 | sort) |
	# Make sure that there are at least 3 field per line
	# -> prevents "cut" from printing wrong values for missing fields
	sed 's/$/\t\t\t/' > commResults
	
	paste -d ',' \
	  <(cut -f 1,3 commResults | tr -d '\t') \
	  <(cut -f 2,3 commResults  | tr -d '\t') |
	sort -t ',' -k 2,2V |
	tr ',' ' ' |
	column -tn
done

rm -f commResults
