#! /bin/bash

# usage:
#        extractResults [DIR_WITH_OUTPUTS]

for i in {10..18}; do
	cat -- "$0/dfs$i"-*.out |
	LC_ALL=C sort -t' ' -k 1,1V -k 3,3n | # sort by error number, trace length |
	LC_ALL=C sort -u -t' ' -k 1,1V |
	cat - > result$i.txt
done
