#! /bin/bash

for i in {10..18}; do
	echo "Generating Problem $i"
	bruteforceFile="../bruteforce/Problem$i.c"
	dfsFile="problem$i.c"

	tailStart="$(grep -Fn 'int inputs[]' "$bruteforceFile" | head -n 1 | cut -d: -f1)"
	totalLength="$(wc -l "$bruteforceFile" | cut -d' ' -f1)"
	tailLength="$(( totalLength - tailStart  + 1 ))"

	inputMin="$(grep -Po '#define\s*INPUT_MIN\s*\K.*' -- "$bruteforceFile")"
	inputMax="$(grep -Po '#define\s*INPUT_MAX\s*\K.*' -- "$bruteforceFile")"

	cat \
		<(sed "s#scriptInsertInputMinHere#$inputMin#" -- dfsHead.c | sed "s#scriptInsertInputMaxHere#$inputMax#") \
		<(tail -n "$tailLength" -- "$bruteforceFile") \
		> "$dfsFile"
done

for i in {10..18}; do
	echo "Compiling Problem $i"
	#clang -O3 -o problem"$i" "$dfsFile"
	gcc --std=gnu99 -O3 -o problem"$i" "$dfsFile"
done

echo "Done"
