#! /bin/bash

problemId="$1"
maxInstances="6"

mkdir -p outputs

echo "This is $(hostname)"
for instance in $(seq 1 "$maxInstances"); do
	echo "Starting problem $problemId, instance $instance"
	"./problem$problemId" > "outputs/dfs$problemId-$instance.out" &
done
echo done
