#! /bin/bash

# Change "if if" to "if else if" one after another.
# Outputs of the modified and original program will be compared
# after every modification (replacement of one "if" with "else if")
# in order to find if statements which should not be replaced with "else if".

CFILE="Problem10.c"
CFILE_INC_ELSE_OLD="Problem10-else-old.c"
CFILE_INC_ELSE="Problem10-else.c"
CORRECT_RESULT="correctResult.txt"
COMPILED="./a.out"
INPUT_LENGTH=7

function compile {
	clang -o "$COMPILED" "$1" 
}

function elseAdded {
	(( $(du -b "$CFILE_INC_ELSE_OLD" | cut -f1) < $(du -b "$CFILE_INC_ELSE" | cut -f1) ))
}

compile "$CFILE"
"$COMPILED" "$INPUT_LENGTH" > "$CORRECT_RESULT"

cp "$CFILE" "$CFILE_INC_ELSE"
cp "$CFILE" "$CFILE_INC_ELSE_OLD"

n=0
while true; do
	# replace next "} if" with "} else if"
	cp "$CFILE_INC_ELSE" "$CFILE_INC_ELSE_OLD"
	perl -0777 -pe 's/\}\s*if/\} else if/' "$CFILE_INC_ELSE_OLD" > "$CFILE_INC_ELSE"
	if elseAdded; then
		(( n++ ))
	else
		echo "Added all elses"
		exit 0;
	fi
	compile "$CFILE_INC_ELSE"
	if diff -q "$CORRECT_RESULT" <("$COMPILED" "$INPUT_LENGTH") > /dev/null; then
		# same result
		echo "same $n"
	else
		# different result
		echo "Different result!"
		exit 1
		# TODO skip this replacement, continue
	fi
done
