#! /bin/bash

color1='\033[91m'
color2='\033[96m'
resetcolor='\033[m'

for i in result1?.txt; do
	inputlength="$(grep -Poe 'input length = \K[0-9]+' "$i")"
	tracelengths="$(grep -Poe ' -> \K[0-9]+' "$i" | sort -nr | tr '\n' ' ')"

	printf "$color1"'%s'"$resetcolor $color2"'len=%02d'"$resetcolor" "$i" "$inputlength"
	xargs printf ' %2d' <<< "$tracelengths"
	echo
done
