/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.uni_freiburg.informatik.ultimate.automata.parser.TestGrammar.node;

import de.uni_freiburg.informatik.ultimate.automata.parser.TestGrammar.analysis.*;

@SuppressWarnings("nls")
public final class ANestedWordTestCase extends PTestCase
{
    private TIdUnquoted _testOperation_;
    private PExpression _expression_;
    private PNestedWord _nestedWord_;

    public ANestedWordTestCase()
    {
        // Constructor
    }

    public ANestedWordTestCase(
        @SuppressWarnings("hiding") TIdUnquoted _testOperation_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") PNestedWord _nestedWord_)
    {
        // Constructor
        setTestOperation(_testOperation_);

        setExpression(_expression_);

        setNestedWord(_nestedWord_);

    }

    @Override
    public Object clone()
    {
        return new ANestedWordTestCase(
            cloneNode(this._testOperation_),
            cloneNode(this._expression_),
            cloneNode(this._nestedWord_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANestedWordTestCase(this);
    }

    public TIdUnquoted getTestOperation()
    {
        return this._testOperation_;
    }

    public void setTestOperation(TIdUnquoted node)
    {
        if(this._testOperation_ != null)
        {
            this._testOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._testOperation_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public PNestedWord getNestedWord()
    {
        return this._nestedWord_;
    }

    public void setNestedWord(PNestedWord node)
    {
        if(this._nestedWord_ != null)
        {
            this._nestedWord_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nestedWord_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._testOperation_)
            + toString(this._expression_)
            + toString(this._nestedWord_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._testOperation_ == child)
        {
            this._testOperation_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._nestedWord_ == child)
        {
            this._nestedWord_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._testOperation_ == oldChild)
        {
            setTestOperation((TIdUnquoted) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._nestedWord_ == oldChild)
        {
            setNestedWord((PNestedWord) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
