/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.uni_freiburg.informatik.ultimate.automata.parser.TestGrammar.node;

import de.uni_freiburg.informatik.ultimate.automata.parser.TestGrammar.analysis.*;

@SuppressWarnings("nls")
public final class TPlaces extends Token
{
    public TPlaces()
    {
        super.setText("#places");
    }

    public TPlaces(int line, int pos)
    {
        super.setText("#places");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPlaces(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPlaces(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPlaces text.");
    }
}
