<project name="LlvmirParser" default="generate-all" xmlns:ant="antlib:org.apache.tools.ant">

  <property name="src.dir" location="src/de/uni_freiburg/informatik/ultimate/llvmir/parser"/>
  <property name="grammar.file" location="${src.dir}/LLVMIR.g4"/>
  <property name="output.dir" location="${src.dir}"/>

  <!-- Generate Llvmir parser and lexer with the antlr parser generator -->
  <target name="generate-all" description="Generate ANTLR parser and lexer code">
  	<java classname="org.antlr.v4.Tool"
  	          fork="true"
  	          failonerror="true"
  	          classpath="lib/antlr-4.13.2-complete.jar">
  	      <arg value="-o"/>
  	      <arg value="${output.dir}"/>
  	      <arg value="${grammar.file}"/>
  	    </java>
  </target>
</project>
