<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<artifactId>mavenparent</artifactId>
		<groupId>de.uni_freiburg.informatik.ultimate</groupId>
		<version>0.3.0</version>
		<relativePath>../BA_MavenParentUltimate/pom.xml</relativePath>
	</parent>

	<groupId>de.uni_freiburg.informatik.ultimate</groupId>
	<artifactId>de.uni_freiburg.informatik.ultimate.version</artifactId>
	<version>0.3.0</version>
	<packaging>eclipse-plugin</packaging>

	<properties>
		<!-- https://mvnrepository.com/artifact/io.github.git-commit-id/git-commit-id-maven-plugin -->
		<!-- https://github.com/git-commit-id/git-commit-id-maven-plugin -->
		<git-commit-id-version>9.0.2</git-commit-id-version>
	</properties>

	<build>
		<directory>${project.basedir}/bin</directory>
		<sourceDirectory>${project.basedir}/src</sourceDirectory>
		<outputDirectory>${project.basedir}/bin</outputDirectory>
		<plugins>
			<plugin>
				<groupId>io.github.git-commit-id</groupId>
				<artifactId>git-commit-id-maven-plugin</artifactId>
				<version>${git-commit-id-version}</version>
				<executions>
					<execution>
						<goals>
							<goal>revision</goal>
						</goals>
						<phase>initialize</phase>
					</execution>
				</executions>
				<configuration>
					<generateGitPropertiesFile>true</generateGitPropertiesFile>
					<generateGitPropertiesFilename>${project.basedir}/version.properties</generateGitPropertiesFilename>
					<dotGitDirectory>${workspaceDir}/../../.git</dotGitDirectory>
					<format>properties</format>
					<useNativeGit>true</useNativeGit>
					<skipPoms>false</skipPoms>
					<runOnlyOnce>false</runOnlyOnce>
					<commitIdGenerationMode>flat</commitIdGenerationMode>
					<gitDescribe>
						<skip>false</skip>
						<!-- when the build is triggered while the repo is in "dirty state", append this suffix -->
						<dirty>-m</dirty>
						<!-- Only consider tags matching the given pattern.
						     This can be used to avoid leaking private tags from the repository. -->
						<match>*</match>
						<tags>true</tags>
					</gitDescribe>
					<includeOnlyProperties>
						<includeOnlyProperty>^git.commit.id$</includeOnlyProperty>
						<includeOnlyProperty>^git.commit.id.abbrev$</includeOnlyProperty>
						<includeOnlyProperty>^git.dirty$</includeOnlyProperty>
						<includeOnlyProperty>^git.build.version$</includeOnlyProperty>
						<includeOnlyProperty>^git.branch$</includeOnlyProperty>
					</includeOnlyProperties>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>${maven-clean-version}</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>.</directory>
							<includes>
								<include>version.properties</include>
							</includes>
							<followSymlinks>false</followSymlinks>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
