#! /bin/bash

# Parse the output files of slice.sh and update the overview csv using the
# new results.

cp ../overview-reachability.csv overview.csv
for problemId in {10..14}; do
	while read safeError; do
		if grep -qF "$problemId,$safeError,yes," overview.csv; then
			echo "Conflict! $problemId, $safeError"
			exit 1
		fi
		mv overview.csv overviewOld.csv
		awk -F, "/$problemId,$safeError,/ "'{$3="no";$4="f" $4}; {print}' OFS=, overviewOld.csv > overview.csv
	done < "sresult$problemId.txt"
done
mv overviewOld.csv overview.csv
rm overviewOld.csv
