#! /bin/bash

# Compute the set complement on files containing "error_??" labels.
# A file with containing all labels "error_0" - "error_99"
# will result in the empty file. Empty files will result in
# a file with all 100 labels.

seq 0 99 | sed 's/^/error_/' > allerrors.txt

for i in {10..18}; do
	grep -Fxvf e2result$i.txt allerrors.txt > s2result$i.txt
done

rm allerrors.txt
