package de.uni_freiburg.informatik.ultimate.lib.sifa.concurrent.cfg;

public enum LocationAbstractionType {
	SINGLETON, SPLIT_AT_GUARD, SPLIT_AT_GUARDS_AND_WRITES, SPLIT_AT_LOCKSETS,
	SPLIT_AT_GUARDS_WRITES_AND_LOCKSETS, SPLIT_AT_NONLOCK_GUARDS_WRITES_AND_LOCKSETS, SPLIT_AT_EVERY_LOCATION
}
