/**
 * 
 */
package de.uni_freiburg.informatik.ultimate.ep.interfaces;

import java.util.List;

import de.uni_freiburg.informatik.ultimate.model.GraphType;
import de.uni_freiburg.informatik.ultimate.model.MarkedTrace;

/**
 * @author dietsch
 *
 */
public interface IModifyingTool extends ITool {
	
	/**
	 * This method is called by the core before a tool is executed. 
	 * If the related tool is an analysis tool it should describe the state of the input model after it was processed by it. 
	 * If the related tool is a generative tool it should describe the state of the new model generated by it.     
	 * 
	 * @return A GraphType object which describes the underlying graph structure of a model
	 */
	GraphType getOutputDefinition();
	
	/**
	 * This method can be called by the toolchain to receive a plugins list
	 * of marked traces that can then be passed to an output plugin.
	 * 
	 * @return list of marked traces
	 */
	List<MarkedTrace> getMarkedTraces();
	
}
