#!/bin/sh
if [ ! "$1" ]; then
    echo "First argument has to be the file that we analyze"
    exit
fi

mem=$((STAREXEC_MAX_MEM - 4096))

if [[ $mem -le 0 ]]; then
    echo "star exex max memory (expected: in Mbyte) is $STAREXEC_MAX_MEM and is smaller than 4096"
    exit 1
fi


java  -Dosgi.configuration.area=config/  -Xmx${mem}M -Xss4m -jar ./../Ultimate/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar  -data "$TMPDIR" -tc ./../AutomizerCHC_wBE.xml -s ./../AutomizerCHC_Goto.epf -i "$1" &> output.txt

RESULT_UNSAFE=`cat output.txt | grep "CounterExampleResult"`
RESULT_SAFE=`cat output.txt | grep "PositiveResult"`
RESULT_UNKNOWN_EXCEPTION=`cat output.txt | grep "The toolchain threw an exception"`

if [ "$RESULT_SAFE" ]; then
	echo "sat"
	exit
fi
    
if [ "$RESULT_UNSAFE" ]; then
	echo "unsat"
	exit
fi
    
echo "unknown"
echo ""
cat output.txt



