version: "2"

services:
  ultimate-webbackend:
    build:
      dockerfile: "Dockerfile"
      target: "ultimate-webbackend"
      args:
        ULTIMATE_DIR_TMP: "${ULTIMATE_DIR_TMP-/tmp/ultimate}"
        ULTIMATE_MEMORY_HEAP_INIT: ${ULTIMATE_MEMORY_HEAP_INIT-4M}
        ULTIMATE_MEMORY_HEAP_MAX: "${ULTIMATE_MEMORY_HEAP_MAX-12G}"
        ULTIMATE_MEMORY_STACK_MAX: "${ULTIMATE_MEMORY_STACK_MAX-512M}"
    image: "ultimate-webbackend"
    environment:
      ULTIMATE_BACKEND_HOST: "${ULTIMATE_BACKEND_HOST-localhost}"
      ULTIMATE_BACKEND_PORT: ${ULTIMATE_BACKEND_PORT-8080}
      ULTIMATE_BACKEND_ROUTE: "${ULTIMATE_BACKEND_ROUTE-/api}"
      ULTIMATE_LOG_PATH: "${ULTIMATE_LOG_PATH-/dev/stdout}"
      ULTIMATE_LOG_LEVEL: "${ULTIMATE_LOG_LEVEL-INFO}"
      ULTIMATE_TIMEOUT: ${ULTIMATE_TIMEOUT-90}
    ports:
      - "8080:${ULTIMATE_BACKEND_PORT-8080}"
    restart: "unless-stopped"

  ultimate-webfrontend:
    build:
      dockerfile: "Dockerfile"
      target: "ultimate-webfrontend"
      args:
        ULTIMATE_FRONTEND_BASEURL: "${ULTIMATE_FRONTEND_ROUTE-/website}"
        ULTIMATE_MEMORY_HEAP_INIT: ${ULTIMATE_MEMORY_HEAP_INIT-4M}
        ULTIMATE_MEMORY_HEAP_MAX: "${ULTIMATE_MEMORY_HEAP_MAX-12G}"
        ULTIMATE_MEMORY_STACK_MAX: "${ULTIMATE_MEMORY_STACK_MAX-512M}"
    image: "ultimate-webfrontend"
    environment:
      ULTIMATE_FRONTEND_DEBUG: "${ULTIMATE_FRONTEND_DEBUG-false}"
      ULTIMATE_FRONTEND_MSG_ORIENTATION: "${ULTIMATE_FRONTEND_MSG_ORIENTATION-left}"
      ULTIMATE_FRONTEND_PROTOCOL: "${ULTIMATE_FRONTEND_PROTOCOL-http}"
      ULTIMATE_FRONTEND_HOST: "${ULTIMATE_FRONTEND_HOST-0.0.0.0}"
      ULTIMATE_FRONTEND_PORT: ${ULTIMATE_FRONTEND_PORT-80}
      ULTIMATE_FRONTEND_ROUTE: "${ULTIMATE_FRONTEND_ROUTE-/website}"
      ULTIMATE_BACKEND_PROTOCOL: "${ULTIMATE_BACKEND_PROTOCOL-http}"
      ULTIMATE_BACKEND_HOST: "${ULTIMATE_BACKEND_HOST-localhost}"
      ULTIMATE_BACKEND_PORT: "${ULTIMATE_BACKEND_PORT-8080}"
      ULTIMATE_BACKEND_ROUTE: "${ULTIMATE_BACKEND_ROUTE-/api}"
    ports:
      - "80:${ULTIMATE_FRONTEND_PORT-80}"
    restart: "unless-stopped"
    depends_on:
      ultimate-webbackend:
        condition: service_healthy
