/* This file was generated by SableCC (http://www.sablecc.org/). */

package local.stalin.automata.parser.TestGrammar.node;

import local.stalin.automata.parser.TestGrammar.analysis.*;

@SuppressWarnings("nls")
public final class TStatestoken extends Token
{
    public TStatestoken()
    {
        super.setText("#states");
    }

    public TStatestoken(int line, int pos)
    {
        super.setText("#states");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStatestoken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStatestoken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStatestoken text.");
    }
}
