#!/bin/sh
if [ ! "$1" ]; then
    echo "First argument has to be the file that we analyze"
    exit
fi
Ultimate_OUTPUT=`./../Ultimate/Ultimate --console ./../AutomizerAndBuchiAutomizerCWithBlockEncoding.xml "$1" --settings ./../settings.epf`

RESULT_NOTMEMSAFE=`echo "$Ultimate_OUTPUT" | grep "CounterExampleResult"`
RESULT_PROVEN_TERMINATION=`echo "$Ultimate_OUTPUT" | grep "Buchi Automizer proved that your program is terminating"`
RESULT_UNKNOWN_TERMINATION=`echo "$Ultimate_OUTPUT" | grep "Buchi Automizer is unable to decide termination"`
RESULT_FALSE_TERMINATION=`echo "$Ultimate_OUTPUT" | grep "Nonterminating execution"`

if [ "$RESULT_PROVEN_TERMINATION" ]; then
	echo "YES"
fi
    
if [ "$RESULT_FALSE_TERMINATION" ]; then
	echo "NO"
fi
    
if [ "$RESULT_UNKNOWN_TERMINATION" ]; then
	echo "MAYBE"
fi

if [ "$RESULT_NOTMEMSAFE" ]; then
	echo "MAYBE"
fi

echo ""
echo "$Ultimate_OUTPUT"

#test if we receive output from z3
#./../z3-4.3.2.d548c51a984e-x64-debian-6.0.6/bin/z3 -h
