#!/bin/sh
pushd ../Ultimate > /dev/null
java \
-Dosgi.configuration.area=config/ \
-Xmx40G \
-Xss4m \
-jar plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar \
-data "$TMPDIR" \
-s ./../smtinterpol.epf \
$@
popd > /dev/null

