/*
 * Copyright (C) 2019 Dominik Klumpp (klumpp@informatik.uni-freiburg.de)
 * Copyright (C) 2019 University of Freiburg
 *
 * This file is part of the ULTIMATE TraceCheckerUtils Library.
 *
 * The ULTIMATE TraceCheckerUtils Library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The ULTIMATE TraceCheckerUtils Library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with the ULTIMATE TraceCheckerUtils Library. If not, see <http://www.gnu.org/licenses/>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 * If you modify the ULTIMATE TraceCheckerUtils Library, or any covered work, by linking
 * or combining it with Eclipse RCP (or a modified version of Eclipse RCP),
 * containing parts covered by the terms of the Eclipse Public License, the
 * licensors of the ULTIMATE TraceCheckerUtils Library grant you additional permission
 * to convey the resulting work.
 */
package de.uni_freiburg.informatik.ultimate.lib.tracecheckerutils.partialorder.independence;

import java.util.Arrays;
import java.util.Objects;
import java.util.function.Supplier;
import java.util.stream.Collectors;

import de.uni_freiburg.informatik.ultimate.automata.partialorder.independence.CachedIndependenceRelation;
import de.uni_freiburg.informatik.ultimate.automata.partialorder.independence.IIndependenceRelation;
import de.uni_freiburg.informatik.ultimate.automata.partialorder.independence.ISymbolicIndependenceRelation;
import de.uni_freiburg.informatik.ultimate.automata.partialorder.independence.TimedIndependenceStatisticsDataProvider;
import de.uni_freiburg.informatik.ultimate.core.model.services.ILogger;
import de.uni_freiburg.informatik.ultimate.core.model.services.IUltimateServiceProvider;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.ModelCheckerUtils;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.cfg.structure.IAction;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.cfg.transitions.TransFormulaBuilder;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.cfg.transitions.TransFormulaUtils;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.cfg.transitions.UnmodifiableTransFormula;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.smt.predicates.BasicPredicateFactory;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.smt.predicates.IMLPredicate;
import de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.smt.predicates.IPredicate;
import de.uni_freiburg.informatik.ultimate.lib.smtlibutils.ManagedScript;
import de.uni_freiburg.informatik.ultimate.lib.smtlibutils.SmtUtils;
import de.uni_freiburg.informatik.ultimate.lib.smtlibutils.SmtUtils.SimplificationTechnique;
import de.uni_freiburg.informatik.ultimate.logic.QuantifiedFormula;
import de.uni_freiburg.informatik.ultimate.logic.Script.LBool;
import de.uni_freiburg.informatik.ultimate.logic.Term;
import de.uni_freiburg.informatik.ultimate.util.datastructures.relation.Pair;
import de.uni_freiburg.informatik.ultimate.util.statistics.IStatisticsDataProvider;
import de.uni_freiburg.informatik.ultimate.util.statistics.KeyType;

/**
 * An independence relation that implements an SMT-based inclusion or equality check on the semantics.
 *
 * It is recommended to wrap this relation in a {@link CachedIndependenceRelation} for better performance.
 *
 * @author Dominik Klumpp (klumpp@informatik.uni-freiburg.de)
 *
 * @param <L>
 *            The type of letters whose independence is checked.
 */
public class SemanticIndependenceRelation<L extends IAction> implements IIndependenceRelation<IPredicate, L> {
	/**
	 * Specifies which kind of independence conditions should be generated by the symbolic counterpart of a semantic
	 * independence relation (see {@link IIndependenceRelation#getSymbolicRelation()}).
	 */
	public enum IndependenceConditions {
		/**
		 * No independence conditions can be generated.
		 */
		NONE(false, false),
		/**
		 * Generate sufficient conditions for independence.
		 */
		SUFFICIENT(false, true),
		/**
		 * Generate sufficient conditions for independence, taking into account known conditions.
		 */
		SUFFICIENT_WITH_CONTEXT(true, true),
		/**
		 * Generate necessary-and-sufficient conditions for independence.
		 */
		NECESSARY_AND_SUFFICIENT(true, false);

		private final boolean mRequiresPredicateFactory;
		private final boolean mRequiresConditionGenerator;

		private IndependenceConditions(final boolean requiresPredicateFactory,
				final boolean requiresConditionGenerator) {
			mRequiresPredicateFactory = requiresPredicateFactory;
			mRequiresConditionGenerator = requiresConditionGenerator;
		}

		public boolean requiresPredicateFactory() {
			return mRequiresPredicateFactory;
		}

		public boolean requiresConditionGenerator() {
			return mRequiresConditionGenerator;
		}
	}

	private static final SimplificationTechnique SIMPLIFICATION_TECHNIQUE = SimplificationTechnique.SIMPLIFY_DDA;

	private final IUltimateServiceProvider mServices;
	private final ILogger mLogger;
	private final ManagedScript mManagedScript;
	private final boolean mConditional;
	private final boolean mSymmetric;

	private final IndependenceConditions mSymbolicIndependenceMode;
	private final BasicPredicateFactory mPredicateFactory;
	private final SemanticIndependenceConditionGenerator mIndependenceGenerator;

	private final Statistics mStatistics = new Statistics();

	/**
	 * Create a new variant of the semantic independence relation.
	 *
	 * The returned relation will not offer a symbolic counterpart via {@link #getSymbolicRelation()}. To support
	 * symbolic relations, call one of the other constructors.
	 *
	 * @param mgdScript
	 *            A script that will be used to construct and solve the required SMT queries for independence checks
	 * @param conditional
	 *            If set to true, the relation will be conditional: It will use the given {@link IPredicate} as context
	 *            to enable additional commutativity. This subsumes the non-conditional variant.
	 * @param symmetric
	 *            If set to true, the relation will check for full commutativity. If false, only semicommutativity is
	 *            checked, which subsumes full commutativity.
	 */
	public SemanticIndependenceRelation(final IUltimateServiceProvider services, final ManagedScript mgdScript,
			final boolean conditional, final boolean symmetric) {
		this(services, mgdScript, conditional, symmetric, IndependenceConditions.NONE, null, null);
	}

	/**
	 * Create a new variant of the semantic independence relation.
	 *
	 * @param mgdScript
	 *            A script that will be used to construct and solve the required SMT queries for independence checks
	 * @param conditional
	 *            If set to true, the relation will be conditional: It will use the given {@link IPredicate} as context
	 *            to enable additional commutativity. This subsumes the non-conditional variant.
	 * @param symmetric
	 *            If set to true, the relation will check for full commutativity. If false, only semicommutativity is
	 *            checked, which subsumes full commutativity.
	 * @param symbolicIndependenceMode
	 *            Determines whether the relation offers a symbolic counterpart via {@link #getSymbolicRelation()}, and
	 *            if so, what kind of independence conditions are generated.
	 * @param predicateFactory
	 *            Used for the symbolic relation returned by {@link #getSymbolicRelation()}.
	 *
	 *            See {@link IndependenceConditions#requiresPredicateFactory()
	 *            symbolicIndependence.requiresPredicateFactory()}.
	 * @param independenceGenerator
	 *            Used for the symbolic relation returned by {@link #getSymbolicRelation()}.
	 *
	 *            See {@link IndependenceConditions#requiresConditionGenerator()
	 *            symbolicIndependence.requiresConditionGenerator()}.
	 */
	public SemanticIndependenceRelation(final IUltimateServiceProvider services, final ManagedScript mgdScript,
			final boolean conditional, final boolean symmetric, final IndependenceConditions symbolicIndependenceMode,
			final BasicPredicateFactory predicateFactory,
			final SemanticIndependenceConditionGenerator independenceGenerator) {
		mServices = services;
		mManagedScript = mgdScript;
		mLogger = services.getLoggingService().getLogger(ModelCheckerUtils.PLUGIN_ID);

		mConditional = conditional;
		mSymmetric = symmetric;

		mSymbolicIndependenceMode = symbolicIndependenceMode;
		mPredicateFactory =
				symbolicIndependenceMode.requiresPredicateFactory() ? Objects.requireNonNull(predicateFactory) : null;
		mIndependenceGenerator =
				symbolicIndependenceMode.requiresConditionGenerator() ? Objects.requireNonNull(independenceGenerator)
						: null;
	}

	@Override
	public boolean isSymmetric() {
		return mSymmetric;
	}

	@Override
	public boolean isConditional() {
		return mConditional;
	}

	@Override
	public Dependence isIndependent(final IPredicate state, final L a, final L b) {
		mStatistics.startQuery();
		final var result = toDependence(contains(state, a, b));
		mStatistics.reportQuery(result, mConditional && state != null);
		return result;
	}

	@Override
	public ISymbolicIndependenceRelation<L, IPredicate> getSymbolicRelation() {
		switch (mSymbolicIndependenceMode) {
		case NONE:
			return null;
		case SUFFICIENT:
			return new ConditionGeneratorIndependence(mIndependenceGenerator, false);
		case SUFFICIENT_WITH_CONTEXT:
			return new ConditionGeneratorIndependence(mIndependenceGenerator, true);
		case NECESSARY_AND_SUFFICIENT:
			return new SymbolicSemanticIndependence(mPredicateFactory);
		default:
			throw new IllegalArgumentException("Unsupported symbolic independence mode: " + mSymbolicIndependenceMode);
		}
	}

	@Override
	public IStatisticsDataProvider getStatistics() {
		return mStatistics;
	}

	/**
	 * Implements {@link #isIndependent(IPredicate, IAction, IAction)} but returns {@code UNKNOWN} if the solver is
	 * unable to decide commutativity.
	 */
	private LBool contains(final IPredicate state, final L a, final L b) {
		final IPredicate context = mConditional ? state : null;
		if (context instanceof IMLPredicate) {
			// Locations will be ignored. However, using predicates with the same formula but different locations will
			// negatively affect cache efficiency. Hence output a warning message.
			mLogger.warn("Predicates with locations should not be used for independence.");
		}

		final var compositions = buildCompositions(a, b);
		final var tfAB = compositions.getFirst();
		final var tfBA = compositions.getSecond();

		final LBool subset = checkInclusionWithGuard(context, tfAB, tfBA);
		if (!mSymmetric) {
			return subset;
		}

		return and(subset, () -> checkInclusionWithGuard(context, tfBA, tfAB));
	}

	private final LBool checkInclusionWithGuard(final IPredicate context, final UnmodifiableTransFormula ab,
			final UnmodifiableTransFormula ba) {
		if (context != null && SmtUtils.isFalseLiteral(context.getFormula())) {
			return LBool.UNSAT;
		}

		if (mManagedScript.isLocked()) {
			mLogger.warn("Requesting ManagedScript unlock before implication check");
			final boolean unlocked = mManagedScript.requestLockRelease();
			if (!unlocked) {
				mLogger.warn("Failed to unlock ManagedScript. Unable to check independence, returning UNKNOWN.");
				return LBool.UNKNOWN;
			}
		}

		UnmodifiableTransFormula abWithGuard;
		if (context == null) {
			abWithGuard = ab;
		} else {
			final var guard = TransFormulaBuilder.constructTransFormulaFromPredicate(context, mManagedScript);

			// This composition should not introduce auxVars.
			// Avoid re-trying elimination of auxVars that already could not be eliminated from ab.
			final boolean tryAuxVarElimination = false;
			abWithGuard = compose(guard, ab, tryAuxVarElimination);
		}
		return TransFormulaUtils.checkImplication(abWithGuard, ba, mManagedScript);
	}

	private Pair<UnmodifiableTransFormula, UnmodifiableTransFormula> buildCompositions(final L a, final L b) {
		final UnmodifiableTransFormula tfA = a.getTransformula();
		final UnmodifiableTransFormula tfB = b.getTransformula();

		// Compose the two transition formulas in both orders.
		// For the composition a*b, only spend time eliminating auxVars if it might be used on the right-hand side of an
		// inclusion check, as auxVars on the left-hand side can be skolemized anyway.
		final UnmodifiableTransFormula transFormulaAB = compose(tfA, tfB, mSymmetric);
		// For the composition b*a, always try to eliminate auxVars, because it always appears on the right-hand side of
		// an inclusion check.
		final UnmodifiableTransFormula transFormulaBA = compose(tfB, tfA, true);

		return new Pair<>(transFormulaAB, transFormulaBA);
	}

	private final UnmodifiableTransFormula compose(final UnmodifiableTransFormula first,
			final UnmodifiableTransFormula second, final boolean tryAuxVarElimination) {
		// no need to do simplification, result is only used in one implication check
		final boolean simplify = false;

		return TransFormulaUtils.sequentialComposition(mLogger, mServices, mManagedScript, simplify,
				tryAuxVarElimination, false, SIMPLIFICATION_TECHNIQUE, Arrays.asList(first, second));
	}

	private static LBool and(final LBool lhs, final Supplier<LBool> getRhs) {
		if (lhs == LBool.SAT) {
			return LBool.SAT;
		}
		final LBool rhs = getRhs.get();
		if (rhs == LBool.SAT) {
			return LBool.SAT;
		}
		if (lhs == LBool.UNSAT && rhs == LBool.UNSAT) {
			return LBool.UNSAT;
		}
		return LBool.UNKNOWN;
	}

	private static Dependence toDependence(final LBool value) {
		switch (value) {
		case UNSAT:
			return Dependence.INDEPENDENT;
		case SAT:
			return Dependence.DEPENDENT;
		case UNKNOWN:
			return Dependence.UNKNOWN;
		}
		throw new IllegalArgumentException("Unknown value: " + value);
	}

	/**
	 * A symbolic independence relation that synthesizes predicates under which two given actions would commute wrt.
	 * {@link SemanticIndependenceRelation}. Specifically, the predicates capture precisely what is needed for
	 * commutativity, as opposed to only a sufficient condition.
	 *
	 * @author Dominik Klumpp (klumpp@informatik.uni-freiburg.de)
	 */
	public class SymbolicSemanticIndependence implements ISymbolicIndependenceRelation<L, IPredicate> {
		private final BasicPredicateFactory mFactory;

		public SymbolicSemanticIndependence(final BasicPredicateFactory factory) {
			mFactory = factory;
		}

		@Override
		public IPredicate getCommutativityCondition(final IPredicate condition, final L a, final L b) {
			mStatistics.reportSymbolicConditionComputation();

			final var compositions = buildCompositions(a, b);
			final var tfAB = compositions.getFirst();
			final var tfBA = compositions.getSecond();

			final Term subset = computeInclusionTerm(tfAB, tfBA);
			final Term formula;
			if (!mSymmetric || SmtUtils.isFalseLiteral(subset)) {
				formula = subset;
			} else {
				final Term superset = computeInclusionTerm(tfBA, tfAB);
				formula = SmtUtils.and(mManagedScript.getScript(), subset, superset);
			}
			return mFactory.newPredicate(formula);
		}

		private Term computeInclusionTerm(final UnmodifiableTransFormula lhs, final UnmodifiableTransFormula rhs) {
			final var difference = TransFormulaUtils.intersect(mManagedScript, lhs,
					TransFormulaUtils.negate(rhs, mManagedScript, mServices));

			// Although auxiliary variables can be skolemized, elimination and simplification yields a simpler predicate.
			// This also affects the trace proofs later on, especially if simplification can eliminate a program variable from the condition.
			final boolean tryAuxVarElimination = true;
			final Term nonInclusion =
					TransFormulaUtils.computeGuardTerm(mServices, mManagedScript, difference, tryAuxVarElimination);

			return SmtUtils.not(mManagedScript.getScript(), nonInclusion);
		}

		@Override
		public boolean isSymmetric() {
			return mSymmetric;
		}

		@Override
		public boolean isConditional() {
			return false;
		}
	}

	/**
	 * A symbolic independence relation that uses an {@link SemanticIndependenceConditionGenerator} to generate a
	 * <em>sufficient</em> (but possibly not necessary) condition under which two given statements commute semantically.
	 *
	 * @author Dominik Klumpp (klumpp@informatik.uni-freiburg.de)
	 */
	public class ConditionGeneratorIndependence implements ISymbolicIndependenceRelation<L, IPredicate> {
		private static final boolean QUANTIFY_IRRELEVANT_CONTEXT_VARS = true;

		private final SemanticIndependenceConditionGenerator mGenerator;
		private final boolean mIsConditional;

		public ConditionGeneratorIndependence(final SemanticIndependenceConditionGenerator generator,
				final boolean conditional) {
			mGenerator = generator;
			mIsConditional = conditional;
			assert mGenerator.isSymmetric() == mSymmetric : "Symmetry of relation and generator does not match";
		}

		@Override
		public IPredicate getCommutativityCondition(final IPredicate condition, final L a, final L b) {
			mStatistics.reportSymbolicConditionComputation();

			if (mIsConditional && condition != null) {
				final var generated = mGenerator.generateCondition(condition, a.getTransformula(), b.getTransformula());
				if (generated == null) {
					return null;
				}
				if (!QUANTIFY_IRRELEVANT_CONTEXT_VARS) {
					return mPredicateFactory.and(condition, generated);
				}

				final var conjunction =
						SmtUtils.and(mManagedScript.getScript(), condition.getFormula(), generated.getFormula());
				final var irrelevantVars = condition.getVars().stream()
						.filter(pv -> !SemanticConditionEliminator.isRelevant(condition, a)
								&& !SemanticConditionEliminator.isRelevant(condition, b))
						.map(pv -> pv.getTermVariable()).collect(Collectors.toList());
				final var quantified = SmtUtils.quantifier(mManagedScript.getScript(), QuantifiedFormula.EXISTS,
						irrelevantVars, conjunction);
				return mPredicateFactory.newPredicate(quantified);

			}
			return mGenerator.generateCondition(a.getTransformula(), b.getTransformula());
		}

		@Override
		public boolean isSymmetric() {
			return mSymmetric;
		}

		@Override
		public boolean isConditional() {
			return mIsConditional;
		}
	}

	private final static class Statistics extends TimedIndependenceStatisticsDataProvider {
		private static final String SYMBOLIC_CONDITION_COMPUTATIONS = "Symbolic Condition Computations";
		private int mSymbolicConditionComputations;

		public Statistics() {
			super(SemanticIndependenceRelation.class);
			declare(SYMBOLIC_CONDITION_COMPUTATIONS, () -> mSymbolicConditionComputations, KeyType.COUNTER);
		}

		public void reportSymbolicConditionComputation() {
			mSymbolicConditionComputations++;
		}
	}
}
